### ISSUE TITLE
Return better error messages

### ISSUE THREAD

**Issue by jonathandturner** [jonathandturner/rhai#1]
Currently, Rhai doesn't track source positions so errors have no location information.  Additionally, it doesn't track the names of where errors occurred (eg: Variable not found vs Variable 'a' not found).

**Comment by juanibiapina** [comment]
Also many errors are returns as Function not found, including some type errors.

**Comment by luciusmagn** [comment]
That's true, it is currently a limitation of our current design. We have polymorphism by just defining more functions registered with the same name to the Rhai engine. Therefore, if a type is wrong, we just assume that the proper variant doesn't exist

**Comment by stevedonovan** [comment]
It certainly would be useful if the error would specify the types for which
the function could not be resolved.

**Comment by schungx** [comment]
PR https://github.com/jonathandturner/rhai/pull/98 now has pretty comprehensive error reporting.  For most uses it should be enough unless we are dealing with very complicated, very large scripts...

Closing for now.
