### ISSUE TITLE
Question: How to bring references into scope?

### ISSUE THREAD

**Issue by matthiasbeyer** [jonathandturner/rhai#10]
Hi,

I have a problem: I'm trying to use rhai to implement a filter type for my imag library, but I fail to bring an object into scope which I have as reference. Here's the codebase: https://github.com/matthiasbeyer/imag/pull/371/files

Note that the `Filter` trait provides a function `filter` which gets a `&Entry`. I need to bring this reference into scope of rhai, but I fail to do so. As you can see I added a wrapper type, but it doesn't help.

Maybe you have an idea?

**Comment by jonathandturner** [comment]
Rhai currently has a few limitations around what argument types it can handle, so it ends up using a few conventions.

One of these conventions is that to make a method, the first parameter has to be '&mut self' rather than '&self'.  I'd like to remove this restriction in the future, if possible.

**Comment by matthiasbeyer** [comment]
Yes, this would be a really nice enhancement I guess, as it would solve my issue here.

**Comment by jonathandturner** [comment]
Took some time today to look into this one a bit more.  It sounds like it may take a while, unless I to find a new trick.  The current approach appears to require impl specialization (https://github.com/rust-lang/rfcs/pull/1210) to finish landing and become widely available in order to support the &T in addition to T and &mut T.

**Comment by schungx** [comment]
Not quite.  It is possible, but you have to specify the exact trait:

```
RegisterFn::<_, (Ref<TestStruct>,), INT>::register_fn(
        &mut engine, "action", |obj: &TestStruct| obj.x,
);
```
