### ISSUE TITLE
Benchmarking Rhai

### ISSUE THREAD

**Issue by schungx** [jonathandturner/rhai#101]
I think some formal benchmarks will be great.

I don't really have large/complex enough scripts to really do a meaningful benchmark. And I'm not really an expert in this... nor do I have access to proper system for this.

Furthermore, what is more important to measure?  Parsing speed?  Evaluation speed?  Memory/CPU footprint?

Suggestions?

**Comment by KaiserKarel** [comment]
So if we'd be able to store ASTs; I'd consider parsing/optimization benchmarks separately from the actual engine benchmarks.

Some things I'd be interested in are:

1. Overhead of calling host functions (expensive computations can be offloaded to the host, if the overhead is low).
2. Some common benchmarks, such as Mandelbrot etc. These are easy enough to implement and give an indication of evaluation speed.
3. Memory and CPU are important as well; but unless we have a stdlib, or a set of prominent scripts to benchmark as part of the CI, we'd have little use for them? I'm guessing these benchmarks would be used to detect perf regressions.

With benchmarking, simply running them on your local laptop would provide little information, as the actual runtimes may wildly differ depending on the system it is run on. I'd say we create a small bench suite, and run those in the CI on PRs. That way we'd have some meaningful, reproducible feedback.

**Comment by schungx** [comment]
1. Overhead of calling registered native functions should be very low, as essentially it is basically calling through a function pointer.  All of the overheads should be in setting up and copying the arguments.

2. I did put in a prime numbers sample, and it doesn't seem like Rhai is very fast compared to a compiled program.  However, it seems fast enough... not sure when running thousands of times though.

3. We can probably start with the prime numbers sample to detect regression...

**Comment by KaiserKarel** [comment]
I can have a look at writing a PR this weekend, to add some benchmarks and possibly include them in CI.

**Comment by schungx** [comment]
I figured that, since Rhai is treating every single value as a dynamic trait object `dyn Any`, requiring an allocation for _every single value_ that ever occurs in the script, it might be best to try to cut down on some of those allocations.  Otherwise large complex scripts are going to be heavily dragged down.

I have a new branch set up on my repo https://github.com/schungx/rhai/tree/enum-Dynamic that changes `Dynamic` to an internal enum that is essentially a union of most of the built-in types.  Other customer types are still represented by a `dyn Any` trait object.

During my preliminary testing on the example scripts, `speed_test.rhai` runs around 50% faster - it completes one million iterations in 1.7 seconds instead of 2.6 before - I have no idea _what_ kind of 5 year-old laptop @jonathandturner  was using to run it in 0.75 second!  I'd love to have one myself!

`primes.rhai`, which is a more complex script with more calculations, runs 5x faster.  I think the difference being `speed_test.rhai` only ever uses one single variable (although it creates one million allocated instances of the values!) while `primes.rhai` creates a _lot_ more values due to heavy calculations.

**Comment by schungx** [comment]
Update: changing toolchain (on Windows) to `stable-i686-pc-windows-gnu` from `-msvc` makes `primes.rhai` run even faster, 8x faster than before.  So, I think LLVM does a better optimization job than MSVC (or Rust is optimized to LLVM)...

64-bit `stable-x86_64-pc-windows-gnu` runs slightly faster than 32-bit on Windows.

**Comment by GopherJ** [comment]
@schungx would you interested in bench over: https://github.com/Knetic/govaluate

**Comment by schungx** [comment]
That would be good, although it does seem to only benchmark relatively small scripted expressions, but those are usually the bulk of a script's workload.

Should be quite simple to translate into Rhai.  However, I think maybe we need to throw in a larger, more complex test script somewhere...

**Comment by jonathandturner** [comment]
@schungx - yeah, I must have hit some of those llvm improvements. If I remember right, I was on macOS at the time, so that would be llvm.

**Comment by schungx** [comment]
>  I was on macOS at the time

LOL probably one of those ultra-high-end, really expensive Macbooks...

**Comment by schungx** [comment]
> 
> 
> @schungx would you be interested in doing a bench to compare with: https://github.com/Knetic/govaluate

@GopherJ  Before we do benchmarks, I suppose we should wait until I merge in the `enum` version of `Dynamic` values.  The current implementation based on `dyn Any` trait objects is never going to win any performance races...

**Comment by KaiserKarel** [comment]
Actually, we should get some benchmarks merged before that, and compare the differences between the enum and Any version. ;)

**Comment by schungx** [comment]
>  compare the differences between the enum and Any version. ;)

I'm quite sure that would be >10x to 100x on most complex benchmarks LOL!

**Comment by schungx** [comment]
> https://github.com/Knetic/govaluate

@GopherJ  it took just a few minutes to actually port the `govaluate` benchmarks to Rhai.  Here are the results:

Test|Timing
---|---
test bench_iterations_1000|   1,870,790 ns/iter (+/- 1,019,604)
test bench_parse_single_parse|         763 ns/iter (+/- 341)
test bench_parse_simple_parse|       4,873 ns/iter (+/- 1,054)
test bench_parse_full_parse  |      20,754 ns/iter (+/- 3,721)
test bench_parse_primes (primes.rhai)     |      56,155 ns/iter (+/- 11,196)
test bench_eval_expression_single          |          76 ns/iter (+/- 24)
test bench_eval_expression_number_literal  |         760 ns/iter (+/- 87)
test bench_eval_expression_number_operators|       1,414 ns/iter (+/- 309)
test bench_eval_scope_single  |         768 ns/iter (+/- 168)
test bench_eval_scope_multiple|         779 ns/iter (+/- 445)
test bench_eval_scope_longer  |       2,241 ns/iter (+/- 639)
test bench_eval_scope_complex |       2,038 ns/iter (+/- 1,272)
test bench_type_field             |         832 ns/iter (+/- 436)
test bench_type_method            |         594 ns/iter (+/- 164)
test bench_type_method_with_params|         840 ns/iter (+/- 283)
test bench_type_method_nested     |       1,557 ns/iter (+/- 778)

I have a Surface Pro 4 i5 which will not break any speed records, but still it seems like the Rust versions are quite a bit slower than `govaluate` in evaluations, but much faster in parsing.

Anyone interested in this can surf to my repo 
https://github.com/schungx/rhai

**Comment by schungx** [comment]
> I'm quite sure that would be >10x to 100x on most complex benchmarks LOL!

I was wrong!  Learnt yet the same lesson (over and over again) - always benchmark and profile before saying anything!

Test|enum Dynamic|dyn Any|
---|---|---
test bench_iterations_1000|   1,870,790 ns/iter (+/- 1,019,604) | 2,267,275 ns/iter (+/- 1,770,665)
test bench_parse_single_parse|         763 ns/iter (+/- 341) | 776 ns/iter (+/- 305)
test bench_parse_simple_parse|       4,873 ns/iter (+/- 1,054) | 5,128 ns/iter (+/- 1,186)
test bench_parse_full_parse  |      20,754 ns/iter (+/- 3,721) | 22,723 ns/iter (+/- 6,244)
test bench_parse_primes      |      56,155 ns/iter (+/- 11,196) | 59,193 ns/iter (+/- 18,476)
test bench_eval_expression_single          |          76 ns/iter (+/- 24) | 130 ns/iter (+/- 40)
test bench_eval_expression_number_literal  |         760 ns/iter (+/- 87) | 906 ns/iter (+/- 367)
test bench_eval_expression_number_operators|       1,414 ns/iter (+/- 309) | 1,666 ns/iter (+/- 327)
test bench_eval_scope_single  |         768 ns/iter (+/- 168) | 898 ns/iter (+/- 254)
test bench_eval_scope_multiple|         779 ns/iter (+/- 445) | 924 ns/iter (+/- 182)
test bench_eval_scope_longer  |       2,241 ns/iter (+/- 639) | 2,592 ns/iter (+/- 990)
test bench_eval_scope_complex |       2,038 ns/iter (+/- 1,272) | 2,684 ns/iter (+/- 2,362)
test bench_type_field             |         832 ns/iter (+/- 436) | 757 ns/iter (+/- 297)
test bench_type_method            |         594 ns/iter (+/- 164) |  500 ns/iter (+/- 112)
test bench_type_method_with_params|         840 ns/iter (+/- 283) | 961 ns/iter (+/- 692)
test bench_type_method_nested     |       1,557 ns/iter (+/- 778) | 1,624 ns/iter (+/- 1,093)

This shows really how useless micro-benchmarks are...  The actual `primes.rhai` script runs 6-8x faster with `enum Dynamic`...

**Comment by GopherJ** [comment]
@schungx Yes it seems slower on evaluations, benchmark is important to know the CS stuff:) I'd like that we can add this bench test suite in rhai.

**Comment by schungx** [comment]
> Can we have bench also for creating instances of `Engine` and register functions because it seems heavy in the flamegraph that we did for casbin-rs: [casbin/casbin-rs#109 (comment)](https://github.com/casbin/casbin-rs/issues/109#issuecomment-612843995)

Try `Engine::new_raw()`.  It should be much lighter, but does not register any standard library functions.  Should be perfect for your case.

**Comment by timfish** [comment]
I tried the benchmarks on my Windows machine with a desktop class i7-8700.
It shows the same ratios/results as seen by @schungx, the only difference being that this CPU appears to have twice the grunt.

Test|enum Dynamic|dyn Any|
---|---|---
test bench_iterations_1000|   833,840 ns/iter (+/- 26,362) |  1,082,180 ns/iter (+/- 29,553)
etc|...|...

**Comment by schungx** [comment]
Some pretty good news.  An attempt to make the `Dynamic` type as small as possible (down to 8 bytes for 32-bit builds without floats and i64, and 16 bytes for 64-bit builds) yielded some pretty significant speed improvements.

**Comment by schungx** [comment]
PR https://github.com/jonathandturner/rhai/pull/144 is now _significantly_ faster (20x for the `primes.rhai` script).

This is achieved via "deep-linking" - meaning to pass around mutable references as much as possible to minimize data copying.  I have been trying to make this change for a long time, did it four times before finally finding a solution to get the borrow checker off my back.

It also solves the ages-long problem of not able to modify a deeply-nested chain of arrays and dot properties.

**Comment by schungx** [comment]
PR https://github.com/jonathandturner/rhai/pull/152 has another speed boost.  Particularly, it eliminates an allocation during each function call, resulting in significant speed improvements for scripts with lots of operator usage.

**Comment by schungx** [comment]
Rhai appears to be fast enough right now. Some benches at https://schungx.github.io/rhai/dev/bench/

I believe most of the low-hanging fruits have already been plucked.  To gain more speed, we have to go into byte-codes.  We now need to balance this with new features we can add for the same amount of developer time.

To put things into context, the `speed_test` script now runs in 0.25 seconds on a 2.3GHz standard cloud Linux VM.  Running the `fibonacci` script for 28 levels is 0.7 seconds.  Comparing it with `wren` benchmarks (http://wren.io/performance.html), it is not too far off, considering that the CPU running the `wren` benchmark has roughly twice the processor throughput.  So I estimate the equivalent speed to be around 0.4-0.5 seconds on the `wren` machine, compared with 0.2 seconds for `wren`.  This puts Rhai up to the speed level of Python at least.

Again, your milage may vary based on your usage scenario.  If you only need to crunch basic data and not interop with Rust functions/types at all, you'll be penalized for this flexibility (because during every operator/function call, the engine asks... "is this function overloaded? ... Hhmmm... no, built-in version then.").
