### ISSUE TITLE
no method named `register_fn` found for type `rhai::Engine` in the current scope

### ISSUE THREAD

**Issue by MasonRemaley** [jonathandturner/rhai#12]
I'm getting the above error on the following source code. I ran `cargo doc` and the function seems to exist so probably a silly mistake on my part and not a bug, but I can't figure out what's going wrong.

```Rust
extern crate rhai;
use rhai::Engine;

fn add(x: i64, y: i64) -> i64 {
	x + y
}

fn main() {
    let mut engine = Engine::new();
    engine.register_fn("add", add); // "no method named `register_fn` found for type `rhai::Engine` in the current scope"
}
```

**Comment by jonathandturner** [comment]
```register_fn``` is part of another trait currently.  You'll need to also use that trait:

```rust
use rhai::{Engine, FnRegister};
```

instead of:

```rust
use rhai::Engine;
```

**Comment by MasonRemaley** [comment]
That'd do it, it's not the first time I've made that mistake and wondered why my methods didn't exist. :) Thanks!
