### ISSUE TITLE
Roadmap for 1.0.0

### ISSUE THREAD

**Issue by GopherJ** [jonathandturner/rhai#126]
rhai is cool, I'm looking forward to seeing `rhai@1.0.0`, I saw many issues with the label `pre-1.0.0 feature`, can we have a roadmap checklist for this? So that the users and developers are clear.

**Comment by schungx** [comment]
https://github.com/jonathandturner/rhai/issues/100

**Comment by GopherJ** [comment]
cool @schungx thanks and sorry that I didn't see it. can it be pinned?
