### ISSUE TITLE
Running untrusted scripts

### ISSUE THREAD

**Issue by KaiserKarel** [jonathandturner/rhai#127]
Is rhai properly sandboxed, akin to Wasm? Meaning that I can safely run arbitrary scripts provided by users? 

This might be same valuabe information for the readme as well.

**Comment by schungx** [comment]
Yes, it is sandboxed.  Only expose functions that you allow the script to call.

See https://github.com/jonathandturner/rhai/issues/102

**Comment by KaiserKarel** [comment]
Thanks for the quick response!
