### ISSUE TITLE
publish a new version with `sync` feature to crates.io

### ISSUE THREAD

**Issue by GopherJ** [jonathandturner/rhai#129]
run `cargo test` on the following code will report errors because: **`(dyn rhai::any::Any + 'static)` cannot be shared between threads safely**
```rust
use rhai::{Engine, EvalAltResult};

fn main() -> Result<(), EvalAltResult> {
    let mut engine = Engine::new();

    let result = engine.eval::<isize>("40 + 2")?;

    println!("Answer: {}", result); // prints 42

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn is_send<T: Send>() -> bool {
        true
    }

    fn is_sync<T: Sync>() -> bool {
        true
    }

    #[test]
    fn test_send_sync() {
        assert!(is_send::<EvalAltResult>());
        assert!(is_sync::<EvalAltResult>());
    }
}
```

**Comment by schungx** [comment]
Check out the `sync` feature.

**Comment by GopherJ** [comment]
the package `test-rhai` depends on `rhai`, with features: `sync` but `rhai` does not have these features.

**Comment by schungx** [comment]
I'll probably show up as a version `0.12.0` in a bit...

In the meantime, I think you can pull from a specific version or commit so you won't have to worry about newer versions?

**Comment by GopherJ** [comment]
Could you publish a new version after making `Any::downcast_ref` public? So that I can try to update to that version

**Comment by GopherJ** [comment]
@schungx  I prefer waiting for the next release because it's not urgent.

**Comment by schungx** [comment]
Alright you got it.  `0.11.1` published to `crates.io`.

**Comment by GopherJ** [comment]
thanks @schungx
