### ISSUE TITLE
Operators for string

### ISSUE THREAD

**Issue by gemmarx** [jonathandturner/rhai#13]
I want infix operators for string to compare("==") and concat.

Rust have no concat op. for &str or String, but they are useful in other languages.
  Fortran:  s = x // y
  Perl:  $s = $x . $y
  Java:  s = x + y
  Lua:  s = x .. y
  VisualBasic:  s = x & y

Would you consider to implement it in Rhai?

**Comment by jonathandturner** [comment]
Added.  Should be in the new 0.4

Btw, you can concat two Strings in Rust (here, foo and bar) doing this:

```rust
foo + &bar
```

**Comment by gemmarx** [comment]
Oh, thank you.

String + &str
Now that you mention it.
