### ISSUE TITLE
Feature: Variadic Functions

### ISSUE THREAD

**Issue by jhwgh1968** [jonathandturner/rhai#132]
This is partly a "nice to have" feature, partly a way to simplify some of the `Fn` trait stuff that Rhai currently uses. (cc @schungx)

The usage would be simple. After calling `register_varargs_fn` on a Rust function called `sum`, you could write this Rhai code:
```
let three = sum(1, 2);
let six = sum(1, 2, 3);
let nine_point_zero = sum (1, 2, 3, 3.0);
```

Simply by using an iterator on the Rust side, the function could take arbitrary parameters and unwrap them dynamically:
```
/* e is the scope of the engine that called us */
fn sum<'e>(args: impl IntoIterator<Iterator=Dynamic + 'e>) -> Result<Dynamic + 'e, rhai::Error> {
    let total = 0.0f32;
    let return_float = false;
    for i in args.into_iterator() {
        if let Some(i32_box) = i.down_cast::<i32>() {
            total += *i32_box as f32;
        } else if let Some(f32_box) = i.down_cast::<f32>() {
            total += *f32_box;
            return_float = true;
        } else if let Some(i64_box) = i.down_cast::<i64>() {
            /* etc ... */
        } else {
            return Err(rhai::Error::new("only float and integer values allowed"));
        }
    }
    Ok(Box::new(if return_float { total } else { total as i32 }))
}
```

How could this be used to simplify `register_fn` and all the `Fn` traits? By making a procedural macro definition, which allowed people to write this:
```
#[rhai::callable]
fn my_function() {
  // ...
}

fn main() {
    let e = Engine::new();
    e.register_fn(my_function); // regardless of parameters, this works!
```

The procedural macro would basically convert every function to a wrapper, which behaves as a varadic function and enforces the count (and perhaps even type) of the arguments passed in from Rhai code.

**Comment by schungx** [comment]
Well, you can pass an array as parameter which will do everything you need.

Maybe some form of syntactic sugar that transforms a variadic fn definition (e.g. `fn abc(..args)`) into `fn abc(args) { args is array }`.

**Comment by jhwgh1968** [comment]
I understand that passing an array can solve the specific problem most of the time. I am suggesting it for its potential future uses, as Rhai (I hope) grows into a full scripting language.

I currently have an unpublished patch to allow fallible conversion of strings to integers. Ideally, I would like an API like the one Python has:
```
let x_str = "31";
let x_int = x_str.to_int(); // 31
let x_hex = x_str.to_int(16); // 49
let x_trinary = x_str.to_int(3); // throws exception
```

However, this is not supported today. Instead, I will have to create two separate methods:
```
let x_int = x_str.to_int();
let x_hex = x_str.to_int_base(16);
```

That example is not a big deal, but as I write more code it could become a bigger disadvantage as methods proliferate. I think of Rhai as a scripting language like Javascript or Python, and this kind of method overloading is common in such languages.

My second point in the OP was about a longer term value this could have: making all sorts of API problems between Rhai and Rust easier to solve. Implementing a Varadic API would be a building block that would support completely getting rid of all the special cases of `register_*_fn`, and allow additional cases to not be special.

However, I realize I probably buried the leade a bit. I'll make that a separate issue.

**Comment by schungx** [comment]
> owever, this is not supported today. Instead, I will have to create two separate methods:

You don't have to.  Rhai can overload.  Just create two new versions of `to_int`, one takes one `&mut` parameter and one takes an additional `INT` parameter.

But again, you must take care to check that the base is never negative or zero etc.

**Comment by schungx** [comment]
>  this could have: making all sorts of API problems between Rhai and Rust easier to solve

Not really.  This will only benefit functions that have an unknown number of arguments that must be handled at runtime.

You can have as many versions of different functions of different number of parameters with the same name in Rhai.

**Comment by jhwgh1968** [comment]
Sorry, I somehow missed overloading. That's good to know!

In that case, I will explain my bigger idea in another issue, and close this one.
