### ISSUE TITLE
Parse error against negative sign

### ISSUE THREAD

**Issue by gemmarx** [jonathandturner/rhai#14]
Parser cannot seem to handle negative sign.
Two evals below print "Can't parse: Minus" in stdout, and ErrorFunctionArgMismatch is returned.

``` rust
engine.eval::<i64>("var n = -1; n");
engine.eval::<i64>("-1+5");
```

**Comment by gemmarx** [comment]
About this theme, issue #25 has been opened.
Thanks :-)

**Comment by luciusmagn** [comment]
I have already implemented unary operators in my local copy and hopefully, will be merging soon!
