### ISSUE TITLE
Efficient Array conversion

### ISSUE THREAD

**Issue by void-dragon** [jonathandturner/rhai#141]
Is there an efficient way to cast a multi dimensional array from rhai to rust?

in rhai
```rust
const data = [[0, 0], [1, 2]]
fn get_sample() {
  data
}
```

in rust
```rust
let data: Array = engine.call_fn0(&mut scope, &ast, "get_sample).unwrap();
// let real_data: Vec<Vec<i32>> = data.cast();
```
Because iterating over the array and casting every item manually seems quite unintuitive and slow.
Or did i miss anything in the documentation?

**Comment by schungx** [comment]
I'm going to merge a PR very soon that converts type `Dynamic` type to one that is an `enum` containing wrapped values of most of the supported standard types.  This feature is possible to add after that landed.

**Comment by schungx** [comment]
I had a little more experimenting about this, and not as easy as it seems.

It will be easy to cast `Vec<T>` but not as easy to cast `Vec<Vec<T>>` etc.  I can probably write a macro to do casting chains up to, say, 10 levels deep, but I wonder if it is going to be useful since you can probably write your own conversion functions much more easily.

```rust
let real_data = data.into_iter().map(|v1 v1.into_iter().map(|v2| v2.cast::<i64>()).collect::<Vec<_>>()).collect::Vec<_>();
```

**Comment by void-dragon** [comment]
One layer would be good enough, which hopefully reduces the main overhead.
Thank You :)

**Comment by schungx** [comment]
If it is one layer, it is extremely simple to do:

```rust
fn cast_array<T: Clone>(data: Array) -> Vec<T> {
    data.into_iter().map(|v| v.cast::<T>).collect()
}
```

**Comment by void-dragon** [comment]
indeed, thats what i am doing now, for every entry in the sub array.
But since the Array type is already a Vec, i hoped for a way to convert the array without touching each element, because i am writing a neuronal network tool and have to shovel around big arrays of floats. So i was hoping for something dirty like `std::mem::transmute`.

As a side note: you can still use LLVM and just in time compile, then the memory area can just unsafely cast to an  `Vec<f32>` :D

But i will just define my own array buffer struct, this should solve the problem as well.
And using Serde for interfacing with json-like data structures would a little bit overkill, but really handy.

**Comment by schungx** [comment]
Unfortunately you won't avoid touching the `Vec` because the sizes are different.  A `f64` is 8 bytes, while the smallest `Dynamic` for 32-bit systems is 16 bytes.  You also cannot just cast it, otherwise it would be a very simple recasting using `unsafe`.
