### ISSUE TITLE
enrich timestamp

### ISSUE THREAD

**Issue by GopherJ** [jonathandturner/rhai#143]
Recently I would like to try to implement this type of ABAC rule in casbin-rs

> If it's around 7am -> 6pm, users can read certain data. 

in casbin-rs we write policy like this

p, hour() > 8 && hour() < 18, read, /data1

but now rhai just support elapsed, is there a way for doing this or it's better to do it on the side of casbin-rs like register an hour function?

**Comment by GopherJ** [comment]
Closed because maybe I should do it in rust level and pass constant to rhai

**Comment by schungx** [comment]
Agreed.  Doing it at Rust level makes the most sense.  Rhai really doesn't want to deal with timezones, DST etc.
