### ISSUE TITLE
0.13.0 fails to compile on 1.42 with missing definition for <integral>::MAX

### ISSUE THREAD

**Issue by sergeken** [jonathandturner/rhai#145]
The release on crates.io fails to compile arithmetic.rs and token.rs with 1.42.
The fix is to add
token.rs : use std::i16
arithmetic.rs : use std::{i32,u32}

**Comment by schungx** [comment]
Oops.  Yes, it isn't necessary for 1.43.  Bummer.

You think I should put out a 0.13.1 for this?  Or wait until everybody upgrades to 1.43?

**Comment by sergeken** [comment]
For me, I'm ok with not "fixing" but advise to add it to the release notes or alike.  I'm currently using Debian testing and expect it to upgrade do 1.43 in the coming weeks.  I decided to use distro packages instead of rustup.  I don't know if rust has some provisioning like other languages (c++ with ifdef's) to have release specific compilation.

**Comment by schungx** [comment]
Not sure what the normal way of handling this is in the Rust world...  I'll have to search a bit to see.  I remember certain crates specifying the minimum version of compiler, but many also don't...

When we go to 1.0, I suppose we should be more pragmatic about this kind of breakage....
