### ISSUE TITLE
why Box<EvalAltResult> is necessary in rhai@0.13.0?

### ISSUE THREAD

**Issue by GopherJ** [jonathandturner/rhai#146]
Hello, I just found rhai@0.13.0 needs `Box<EvalAltResult>`, can we know why is it necessary because it seems not necessary. Thanks.

**Comment by schungx** [comment]
That is for reducing the return size of many hot code paths returning simple values or a single `Dynamic`.  Error paths are rare and they tend to terminate the evaluation, so it doesn't hurt to have an additional level of indirection.

My benchmarks show speed improvements around 5-10%, at the expense of having a `Box` in the error.  You can also see more `Box`ing in many data types internally, although they don't affect the API.

**Comment by GopherJ** [comment]
@schungx In this case shall we re-map EvalAltResult - Box<EvalAltResult>? so that users don't need to change their code

**Comment by schungx** [comment]
I thought about that, but then people who `match` on the results are going to get a surprise... There doesn't seem to be a way to make it fool-proof.

Boxing the error reduces, for example, the typical `Result<i32, EvalAltResult>` from 56 bytes to 16 bytes for `Result<i32, Box<EvalAltResult>>`.  If you call `Engine` API's a lot or in a tight loop, that's going to add up.

**Comment by GopherJ** [comment]
ok seems reasonable
