### ISSUE TITLE
Documentation!()

### ISSUE THREAD

**Issue by felipetesc** [jonathandturner/rhai#15]
Great job!
By simply looking the readme file, I found that your job seems very promissing, and I'll, just like many other people, ask you more documentation. I've looked into the project dates, and as I can see, you are changing it  constantly: that's good. I really wanted to use your Script System, but I found a little bit hard with the current state of your examples(docs). It would be nice, if you create a document showing to the people the differences between Rhai to Rust. So if we study Rust, and later on, we can study your language! Presenting a table with the diffrences between the both (Rust and Rhai) may be enough.
Thanks and keep doing it!

**Comment by matthiasbeyer** [comment]
Jup, can't support this enough. I am about to integrate rhai into my project ([imag](https://github.com/matthiasbeyer/imag)) and I'd _love_ some more documentation and also generated github pages!

**Comment by luciusmagn** [comment]
Oh yeah, docs are good. I will add it to TODO and hopefully work on them in the near future

**Comment by KaiserKarel** [comment]
Should we have a Rhai book, mimicing https://doc.rust-lang.org/stable/book/ch01-02-hello-world.html? Probably best post v1.0, once the language and features stabilize a bit.

**Comment by schungx** [comment]
I'm all for more documentation, but as typical for release-quality software, you spend 1 hr writing code and then 5 hours writing documentation and tests and examples...

Somebody needs to come up with the time to gradually do this, I suppose...

**Comment by schungx** [comment]
Closing this one for now.  I feel that at least the `README` has improved to an extent that it should be usable, although still light on examples and tutorials.
