### ISSUE TITLE
Dynamically sized arguments for `Engine::call_fn`

### ISSUE THREAD

**Issue by appellation** [jonathandturner/rhai#157]
Hello! I'm excited to try using Rhai as a scripting language for a Rust project I'm working on, and it looks ideal for my purposes. However, I'm running into an issue where I'd like to dynamically call a Rhai function from Rust with a dynamic amount of arguments.

I'm sure there's some unsafe method to turn a vec into a tuple (as currently required by the API), but it seems unnecessary given that `Engine::call_fn` immediately converts the arguments into a vec anyway. `FuncArgs` doesn't seem to be exposed in the public API either, so I couldn't figure out a clean way to implement it myself.

https://github.com/jonathandturner/rhai/blob/e5584b24710cb3aeb184a8bc1079b9fccf5b68d8/src/api.rs#L1003-L1012

Is there a possibility of getting some functionality like that? I wouldn't want to break the API unnecessarily, so this might require defining another function for this purpose? Perhaps just exposing the `FuncArgs` trait?

My usecase here is evaluating untrusted, user-defined functions with user-defined parameters. Users would be responsible for ensuring that their function signature matches the data being passed in.

Somewhat tangentially, it would be nice to deserialize data into a Dynamic type; the docs show that `Dynamic::from` is implemented for `Variant + Clone` which may be what I'm looking for, but there's no documentation on what a "Variant" is or how I could implement it for all or some serde types.

Thanks!

**Comment by schungx** [comment]
It should be easy to add this into the `Func` trait, something similar to how the `RegisterFn` trait is implemented.

This is how `Variant` is defined:

```rust
pub trait Variant: Any { ... }

impl<T: Any + Clone> Variant for T { ... }
```

So basically `Variant` is  any clonable type.  (If you use `sync`, then it must also be `Send + Sync`).

I suggest you directly implement `serde` for `Dynamic` instead of `Variant` since `Dynamic` holds certain standard types directly and `Variant` is a trait object requiring another level of redirection.

**Comment by schungx** [comment]
I can put in something like the below...

```rust
/// Call a script function defined in an `AST` with multiple `Dynamic` arguments.
///
/// ## WARNING
///
/// All the arguments are _consumed_, meaning that they're replaced by `()`.
/// This is to avoid unnecessarily cloning the arguments.
/// Do you use the arguments after this call. If you need them afterwards,
/// clone them _before_ calling this function.

fn main() -> Result<(), Box<rhai::EvalAltResult>> {
	use rhai::{Engine, Scope};

	let engine = Engine::new();

	let ast = engine.compile(r"
		fn add(x, y) { len(x) + y + foo }
		fn add1(x)   { len(x) + 1 + foo }
		fn bar()     { foo/2 }
	")?;

	let mut scope = Scope::new();
	scope.push("foo", 42_i64);

	// Call the script-defined function
	let result = engine.call_fn_dynamic(&mut scope, &ast, "add", &mut [ String::from("abc").into(), 123_i64.into() ])?;
	assert_eq!(result.cast::<i64>(), 168);

	let result = engine.call_fn_dynamic(&mut scope, &ast, "add1", &mut [ String::from("abc").into() ])?;
	assert_eq!(result.cast::<i64>(), 46);

	let result= engine.call_fn_dynamic(&mut scope, &ast, "bar", &mut [])?;
	assert_eq!(result.cast::<i64>(), 21);
	Ok(())
}
```

**Comment by appellation** [comment]
Thank you for your detailed response. Yes, I'd hoped that my users could avoid dealing with the `Dynamic` struct and could instead provide types roughly matching the form they would expect to receive in the function. That was my expectation when thinking about serde deserialization; I am using JSON, so I expect this to map relatively easily. I hadn't considered that it's possible to implement serde traits on external structs, so I'll look into that.

I completely understand why the API is currently designed around tuples and it definitely makes sense from a UX standpoint. Your example looks like it would work great for what I'm trying to achieve here. I have no need to keep the values after passing them in, and I could clone them before passing them in if I needed to. I'm still a bit new to Rust, so the finer points of optimizing the types themselves is something I believe you'd have more knowledge with.

Thanks for such a quick and detailed response!

**Comment by schungx** [comment]
Yes, you can simply use `engine.parse_json` to get a `rhai::Map` which you can then put into a scope and use in scripts.

Alternatively, since Rhai object notation is almost exactly the same as JSON, you can splice the JSON texts directly into the script prefixed with `#`: `let x = #{a:1, b:true, c:"hello"};` where everything after `#` is JSON.

**Comment by appellation** [comment]
After our discussion, I went ahead and quickly implemented a version (https://github.com/appellation/rhai/commit/4309143a25e63fa99407c3edf877041968a70ecf) of what you were talking about. Is this what you had in mind? I'm happy to open a PR with these changes (obviously with some documentation added to the new method).

**Comment by schungx** [comment]
Similar.  I actually already added it (it is in a PR that'll land today).  I prefer to keep the `call_fn` as is to avoid breaking code, but it just calls in to the new `call_fn_dynamic`.

See https://github.com/jonathandturner/rhai/pull/156/commits/76d792011f72d239f81c22012638b95391c87bf5

**Comment by schungx** [comment]
Version `0.15.0` available from `crates.io` has `call_fn_dynamic`.
