### ISSUE TITLE
Function not found with String parameter

### ISSUE THREAD

**Issue by sergeken** [jonathandturner/rhai#162]
I try to call a registered function from a chai function invoked through call_fn.
I've been trying to debug but without studying the code in detail it isn't that simple.  However, I see that the function is properly registered and stays stored in engine.global_modules.functions during the call to call_fn.

Below to code that exposes the problem.
```rust
use rhai::{Engine, RegisterFn, Scope};

fn price(_name : String) -> f64 {
    0.2
}

fn main() {
    println!("Hello, world!");
    let script = r"
        fn vat(value, rate_name) {
            debug(price(rate_name));
            let rate = price(rate_name);
            value * rate
        }
    ";
    let mut engine = Engine::new();
    let mut scope = Scope::new();
    engine.register_fn("price", price);
    let ast = engine.compile(script).unwrap();
    let vat: f64 = engine.call_fn(&mut scope, &ast, "vat", (123_f64, String::from("abc"))).unwrap();
    println!("vat = {}", vat);
}
```

The programs panics with:
```
 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/bug`
Hello, world!
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorInFunctionCall("vat", ErrorFunctionNotFound("price (string)", 3:15), 0:0)', src/main.rs:20:20
```

**Comment by schungx** [comment]
This is in the `README`.  Rhai uses `ImmutableString`, not `String`:

```rust
fn price(_name : &mut ImmutableString) -> f64 {
    0.2
}
```

Use `&mut` can save an extra cloning.

**Comment by sergeken** [comment]
Works indeed.  Any way to enhance the error reporting to something more useful?  Admit that I've been taken for a ride.
Another side question, why &mut and not &, especially for an object called "ImmutableString".
0.16 will be very welcomed.

**Comment by schungx** [comment]
Well, based on your experience, I've enhanced the error messages in `0.16.0`.  It now says: `function not found: 'price (&str | ImmutableString)'`.  That should be clearer...

Rhai functions can only take one of two forms: 1) all owned values, 2) first parameter `&mut` and the rest owned values.  The second is really for property setters and methods.  You can use the first form, but that means cloning the `ImmutableString` which means incrementing a reference count.  For `sync`, it means incrementing an `Arc` which might be slow.  Therefore use the second form if you don't need to consume the first argument.
