### ISSUE TITLE
Trailing comma in object maps and other places

### ISSUE THREAD

**Issue by alvinhochun** [jonathandturner/rhai#165]
Can the syntax be changed to accept this? Now it is giving a `ParseErrorType::PropertyExpected`.

```rust
let a = #{
    a: 1,
    b: 2, // Trailing comma!
};
```

**Comment by schungx** [comment]
That would make it very Rusty, as most other scripting languages choke on trailing commas.

It shouldn't be difficult to do (only adding an extra match case), but I'm not sure if everyone would want it.

**Comment by alvinhochun** [comment]
> most other scripting languages choke on trailing commas.

JavaScript (except for IE6/IE7 but who cares about them these days), Python and Lua supports trailing comma, I suppose that's mainstream enough?

> It shouldn't be difficult to do (only adding an extra match case), but I'm not sure if everyone would want it.

Perhaps make it configurable? But accepting trailing comma shouldn't break existing scripts so it doesn't seem to be a big issue.

> If we support this, then we should also support trailing commas on function arguments, arrays, export list etc.

Trailing commas everywhere!

**Comment by schungx** [comment]
OK you sold me.

**Comment by schungx** [comment]
OK.  Spent 5 minutes to implement it.  The next version will support trailing commas on arrays, function definitions, function calls and object maps.
