### ISSUE TITLE
Suggestion for the online Rhai book

### ISSUE THREAD

**Issue by alvinhochun** [jonathandturner/rhai#173]
- I think the published version should be for the stable release, as it is the version that most users will actually be using. There can be a separate unstable book for the master branch but it needs to be marked clearly.
- How about setting up a Github organization so the book can live on a (sub-)domain dedicated for Rhai? Also leave room for a homepage in the future (the book should be in a sub-dir).

**Comment by schungx** [comment]
> How about setting up a Github organization so the book can live on a (sub-)domain dedicated for Rhai? Also leave room for a homepage in the future (the book should be in a sub-dir).

That would probably be in the future plans, but I think maybe let's wait until we have a larger users' base in order to justify doing this? Maybe at least 1.0...

In the meantime, we can have different assets in different places...

**Comment by schungx** [comment]
> I think the published version should be for the stable release, as it is the version that most users will actually be using. There can be a separate unstable book for the master branch but it needs to be marked clearly.

Yes, that's my plan.  I plan to officially transition to the book starting from `0.16.0` and so right now that version is only _beta_.

I'll then make a subdirectory (`vnext`?) that contains the book version for this repo.

**Comment by schungx** [comment]
The Rhai Book (`crates.io` version) is at https://schungx.github.io/rhai

The dev version is at https://schungx.github.io/rhai/vnext
