### ISSUE TITLE
serde support for Dynamic values

### ISSUE THREAD

**Issue by alvinhochun** [jonathandturner/rhai#174]
Use cases:

- Rust to Rhai: While it is possible to register custom Rust types, it needs some manual boilerplate code for getters/setters and also gets complicated with nested structures. Allowing easy "serialization" from Rust types to Rhai object maps can bypass all that, with the expense of some run-time performance.
- Rhai to Rust: There is no easy way to construct and return Rust structs from Rhai other than exposing custom functions from Rust. Allowing "deserialization" from Rhai object maps to Rust types can be a straightforward solution.
- Handling Rhai object maps directly is cumbersome due to all values being a `Dynamic`.

**Comment by schungx** [comment]
So you're suggesting a feature that deserializes a `Map` into a Rust type via `serde`?

It would probably be very similar to JSON...  Maybe it is better to do it the other way round - serialize a `Dynamic` into JSON and then let the user deserialize it using whatever method they choose?

I use `serde` but no idea how to provide this feature.  Maybe I'll study other libraries...

**Comment by alvinhochun** [comment]
Actually no, it seems that neither `serde` nor JSON actually makes sense... A custom proc-macro can do much better. Consider something like this:

```rust
struct TestStruct { .. }

impl TestStruct {
    fn new() -> Self { .. }
}

// Imaginary derive macro
#[derive(rhai_derive::FromMap)]
struct SerializeFromRhaiMapType {
    id: String,
    number: i64,
    #[rhai(direct)]
    data: TestStruct,
}


let mut engine = Engine::new();

engine.register_type::<TestStruct>();

engine.register_fn("new_ts", TestStruct::new);

let result = engine.eval::<TestStruct>(r#"
    let x = new_ts();
    #{
        id: "item-01",
        number: 1234,
        data: x,
    }
"#)?;

// Imaginary function
let output: SerializeFromRhaiMapType = rhai::from_map(result)?;
```

You cannot do this with either `serde` or JSON without going through an extra step converting the `TestStruct` into a key-value map and back again.

**Comment by schungx** [comment]
With this macro, we can actually do:

```rust
let output = engine.eval::<SerializeFromRhaiMapType>(r#"
    let x = new_ts();
    #{
        id: "item-01",
        number: 1234,
        data: x,
    }
"#)?;
```

Provided if we register `SerializeFromRhaiMapType` with the `Engine` as a `Map`-convertible type.

**Comment by alvinhochun** [comment]
Right, and then there are also different `enum` representations. How about we just forget the case in my last comment and just make use of `serde`...

I don't really like the idea of building a JSON string just for it to be deserialized immediately.

**Comment by schungx** [comment]
>  just make use of serde...

Yeah, I think that's the best route.  We'll be adding a `serde` feature.

But I'll have to read up on `serde` to know how to do it and what I need to implement.  Do you have an idea?

**Comment by alvinhochun** [comment]
This section (https://serde.rs/data-format.html) explains it a bit.

How I think it should be done:

- Add a crate `rhai-serde` in the same repo as Rhai as a Cargo workspace member
- Make `rhai-serde` depend on `rhai` (can't have it in reverse because `rhai-serde` needs to use `rhai` types)
- Users who needs the function will just add the `rhai-serde` crate

**Comment by alvinhochun** [comment]
Now I'm not really sure if calling it `rhai-serde` is a good idea. This is tangential to the original suggestion, but if at some time Rhai also want to implement the ability to `serde` directly between a Rhai value and a `serde` data format, the naming of things will get pretty confusing.

**Comment by schungx** [comment]
Let's see how much code it'll be.  If not too much, then probably hiding it behind a feature gate is better than creating a workspace and an additional crate...

**Comment by schungx** [comment]
After reading up on `serde` some more, it seems not possible (at least not immediately obviously) to do what we want.

We can do:

`CustomType` <--> `serde` <-- stream --> `serde` <--> `Map` (`HashMap<String, Dynamic`)

but there doesn't seem to be a way to do:

`CustomType` <--> `serde` <--> `Map`

because `serde` works from `Vec<u8>`.  So it really expects to _serialize_ something, not convert between data formats.

To do what we want we'll need:

`CustomType` --> `JSON` --> `Map`

and vice versa, and with JSON support for `Map`'s in Rhai, this route is already useable.

**Comment by alvinhochun** [comment]
Is it really impossible? I'd want to check to see if any other scripting language libraries in Rust are doing this.

I know that wasm-bindgen can use `serde` to convert between Rust type and JavaScript objects, so I thought it should be possible to serialize to something that isn't just raw bytes.

**Comment by schungx** [comment]
It may be possible, but I need to dig it out...  I think the standard functionalities work from streams by default?

**Comment by schungx** [comment]
Hhhhmmm...  may be possible.  You're right.  It does not need to be streams.

**Comment by alvinhochun** [comment]
> > I know that wasm-bindgen can use serde to convert between Rust type and JavaScript objects, so I thought it should be possible to serialize to something that isn't just raw bytes.
> 
> Maybe they use JSON in the back?

I just checked the [docs](https://rustwasm.github.io/wasm-bindgen/reference/arbitrary-data-with-serde.html#an-alternative-approach-serde-wasm-bindgen) again and it turns out the built-in conversion does internally go through JSON. But an [alternative implementation](https://github.com/cloudflare/serde-wasm-bindgen) exists that uses wasm <-> JavaScript calls to build/inspect the JS objects directly.

There is also a crate [`rlua-serde`](https://github.com/zrkn/rlua_serde/) that uses `serde` for a Lua binding. Perhaps these crates can serve as a reference?

**Comment by schungx** [comment]
The latest from https://github.com/schungx/rhai has `serde` support for serialization/deserialization to/from `Dynamic` values.
