### ISSUE TITLE
Alternative trait/lifetime bounds for `Engine` callbacks?

### ISSUE THREAD

**Issue by alvinhochun** [jonathandturner/rhai#178]
This is regarding the methods on `Engine` like `on_print`, `on_debug` or `on_progress`. These functions take a closure of `impl Fn(&_) -> _ + SendSync + 'static`, which means the closure (1) cannot contain any mutable states unless `RefCell` is used, and that it (2) cannot borrow anything that outlives the `Engine` but doesn't have a `'static` lifetime.

An example is https://github.com/alvinhochun/rhai-playground/blob/15a1b7e3b9641647979107cefa486587a0d55057/src/scripting.rs#L27 - this code aims to report script execution progress at a reasonable rate with a bit of time tracking. Note that it has to move `RefCell`s into the closure in order to get mutable states. The lifetime issue happens to not matter here because the JavaScript values are all free-to-copy GC'ed references (i.e. doesn't follow Rust ownership rules), but the same code might not work if it is for a native application, or perhaps it would require making a few thread-local `static RefCell` (or `Mutex` if the `sync` feature is enabled)...

I'm wondering if it makes sense for the closures to be `impl FnMut(&_) -> _ + SendSync + 'self` ('self is a pseudo lifetime) instead, but doing this will require adding a lifetime bound to `Engine` and probably requires the closures to be passed in on construction? Or maybe there should be another way of customizing the `Engine`, like making a trait that users can impl for their custom Engine? (I haven't really thought this through, so please forgive me if it doesn't make sense.)

**Comment by schungx** [comment]
Originally `Engine` had a lifetime, but then it makes it rather ungainly because most uses will be `Engine<'static>`.

Maybe I can make a `RawEngine<'e>` and then `pub type Engine = RawEngine<'static>`?

I'm not sure if it is worth it just for integrating into a GC-ed environment though...  Outside of such environments, it is rather rare.  And, beware, the `Engine` can still not hold mutable pointers, unless all `Fn` gets turned into `FnMut`.

At the current time, it seems that a `RefCell` is a small price to pay for such special scenarios...

**Comment by alvinhochun** [comment]
How about another approach which won't require adding a lifetime to the whole `Engine`:

Make a `ScopedEngine<'_>` that provides only the methods to set temporary callbacks (e.g. `on_print`) and to execute scripts (e.g. `call_fn`, `eval`), with other things borrowed from the original `Engine`, which can be used like this for example:

```rust
fn eval_with_engine(
    engine: &Engine,
    script: &str,
) -> Result<(Dynamic, Vec<String>, u64), Box<EvalAltResult>> {
    let mut output = vec![];
    let mut ops_count = 0;
    let result: Dynamic = engine.scoped(|scoped_engine: &mut ScopedEngine| {
        scoped_engine.on_print(|s| {
            output.push(s.to_owned());
        });
        scoped_engine.on_debug(|s| {
            output.push(s.to_owned());
        });
        scoped_engine.on_progess(|&ops| {
            ops_count = ops;
        });
        scoped_engine.eval(script)
    })?;
    Ok((result, output, ops_count))
}
```

`Engine::scoped` creates a `ScopedEngine` with a reference to `self`, then pass it into the closure (which will be an `FnOnce`) as a `&mut`, and then dropped after the closure returns. The callbacks (`on_print` and etc) are set on the `ScopedEngine` so they won't need a `'static` lifetime and can borrow local variables mutably. These callbacks also override the ones set on the `Engine`.

> I'm not sure if it is worth it just for integrating into a GC-ed environment though...

It's for the opposite (i.e. normal Rust references). I was saying that it doesn't matter for global GC references.


> And it may actually not be very slow... since you're only updating the value infrequently.

It's not just about the speed, but also the ergonomics.

**Comment by schungx** [comment]
But there are a lot more functions in Rhai than just `on_print`, `on_debug` and `on_progress` though...

In fact, every single function right now is limited to being `'static`.  If I can relax this requirement, then a command-control object type of scenario can be built very easily without `RefCell` as I can just pass in a mutable reference to the command object inside a function closure.

**Comment by alvinhochun** [comment]
How about extending ScopedEngine to support everything? As in, make it so that the user can register any custom functions  through it which will be automatically deregistered at the end of the scope.

This would be alike to how rlua handles lifetime.

**Comment by schungx** [comment]
Then it would actually be easier to make `EngineRaw<'e>` and then `type Engine = EngineRaw<'static>`...

**Comment by alvinhochun** [comment]
The ScopedEngine approach would allow for the Engine to be reused across multiple invocations, while the EngineRaw approach would require a new Engine instance for every time.

Is the construction of Engine an expensive operation?

**Comment by schungx** [comment]
> Is the construction of Engine an expensive operation?

`Engine::new()` is... while `Engine::new_raw()` isn't.

> The ScopedEngine approach would allow for the Engine to be reused across multiple invocations, while the EngineRaw approach would require a new Engine instance for every time.

You're probably right, but then `ScopedEngine` is limited to a number of standard operations, such as dumping all `print`/`debug` output to a `Vec`.  And there is no way to terminate a script in the middle via `on_progress` other than to keep counting.

It'll work wonders if those operations happen to be what the users want but...

**Comment by alvinhochun** [comment]
> 
> > The ScopedEngine approach would allow for the Engine to be reused across multiple invocations, while the EngineRaw approach would require a new Engine instance for every time.
> 
> You're probably right, but then `ScopedEngine` is limited to a number of standard operations, such as dumping all `print`/`debug` output to a `Vec`. And there is no way to terminate a script in the middle via `on_progress` other than to keep counting.
> 
> It'll work wonders if those operations happen to be what the users want but...

Most methods in Engine can be implemented for ScopedEngine, I don't see why not.

**Comment by schungx** [comment]
> Most methods in Engine can be implemented for ScopedEngine, I don't see why not.

Yeah, I know.  But my main point is: we can only implement something that we think the user needs.  Such as logging to a `Vec` that practically grows unlimited.

However, what we think the user needs may not be what he really needs...

There is no way for the user to pass in his/her own implementation to these callbacks.  They can, but those callbacks must be `'static` right now.

**Comment by alvinhochun** [comment]
> There is no way for the user to pass in his/her own implementation to these callbacks. They can, but those callbacks must be `'static` right now.

Why not? The point of a ScopedEngine is to allow registering callbacks or callable functions with a scoped lifetime, eliminating the requirement of `'static`, so that they can for example mutate local variables. This can enable some patterns that are currently impossible to implement.

Perhaps you can take a look at how `rlua` handle this with [`scope`](https://docs.rs/rlua/0.17.0/rlua/struct.Context.html#method.scope) ([example](https://github.com/amethyst/rlua/blob/25bd7e6bffef9597466a98bfca80a3056c9e6320/examples/guided_tour.rs#L198)). It doesn't map to Rhai exactly but is a similar idea.

**Comment by schungx** [comment]
Hhhmmm... let me look into this some more...

**Comment by schungx** [comment]
> and can borrow local variables mutabl

Not unless I make the function signatures `FnMut` though... And then the `Engine` instance must itself be mutable.  Otherwise, it can probably _hold_ a reference, but not a mutable one.

**Comment by alvinhochun** [comment]
I imagine it this way: The ScopedEngine inherits everything from the Engine but with the ability to override some aspects of it. The overrides only exists for as long as the ScopedEngine is alive. Any mutations only changes the ScopedEngine so there is no need to mutate the Engine itself.

**Comment by schungx** [comment]
>  The callbacks (`on_print` and etc) are set on the `ScopedEngine` so they won't need a `'static` lifetime and can borrow local variables mutably. These callbacks also override the ones set on the `Engine`.

One question - how do I link up `ScopedEngine`'s `on_print` with the inner `Engine`'s `on_print` which takes only `'static` while `ScopedEngine::on_print` takes a lifetime?

> The ScopedEngine inherits everything from the Engine

In Rust you can't though... there is no inheritance.

**Comment by alvinhochun** [comment]
> 
> 
> > The callbacks (`on_print` and etc) are set on the `ScopedEngine` so they won't need a `'static` lifetime and can borrow local variables mutably. These callbacks also override the ones set on the `Engine`.
> 
> One question - how do I link up `ScopedEngine`'s `on_print` with the inner `Engine`'s `on_print` which takes only `'static` while `ScopedEngine::on_print` takes a lifetime?
> 
> I've looked at `rlua` and there is heavy use of `unsafe` to do this...

I think there should be no issues because `'static` always lives longer than any other lifetimes. `rlua` needs a lot of `unsafe` because it interacts with a C library, but for Rhai it should be solvable without the use of `unsafe`. When you have a reference to it, can't it just be called like normal?


> 
> > The ScopedEngine inherits everything from the Engine
> 
> In Rust you can't though... there is no inheritance.

Not in the OOP sense, but ScopedEngine can contain a reference to the Engine to use its fields.

**Comment by schungx** [comment]
> When you have a reference to it, can't it just be called like normal?

Yes I can call any method and access any field in `Engine`.  However, I cannot hook up to its callbacks since they are `'static`.

I can provide a scoped callback to the outside, but internally there is no way for me to connect the external callback with the internal callback on `Engine`.

**Comment by alvinhochun** [comment]
> 
> 
> > When you have a reference to it, can't it just be called like normal?
> 
> Yes I can call any method and access any field in `Engine`. However, I cannot hook up to its callbacks since they are `'static`.
> 
> I can provide a scoped callback to the outside, but internally there is no way for me to connect the external callback with the internal callback on `Engine`.

Oh, I see what you mean. I was thinking of the reverse - you hook the `Engine`'s callback into the `ScopedEngine` and move the script execution code into `ScopedEngine`, or refactor them somewhere else ~~and then hope that the compiler can optimize them well enough~~, that should solve the lifetime issues?

**Comment by schungx** [comment]
> you hook the `Engine`'s callback into the `ScopedEngine`

But then, inside the closure, `ScopedEngine` must provide the same functionalities, because it cannot delegate back to the original `Engine`.

Therefore, essentially you have what I started off with: `RawEngine<'e>` in the inside, and `type Engine = RawEngine<'static>` on the outside.

**Comment by alvinhochun** [comment]
> 
> 
> > you hook the `Engine`'s callback into the `ScopedEngine`
> 
> But then, inside the closure, `ScopedEngine` must provide the same functionalities, because it cannot delegate back to the original `Engine`.
> 
> Therefore, essentially you have what I started off with: `RawEngine<'e>` in the inside, and `type Engine = RawEngine<'static>` on the outside.

That is somewhat true. Is it possible to make `RawEngine` "inherit" another existing `RawEngine` to avoid needing to create fresh ones every time?

**Comment by alvinhochun** [comment]
> But then, inside the closure, `ScopedEngine` must provide the same functionalities, because it cannot delegate back to the original `Engine`.

Or perhaps you can have the methods in `Engine` create a `ScopedEngine` and delegate to it? Except for the methods that needs to mutate the `Engine`.

**Comment by schungx** [comment]
> That is somewhat true. Is it possible to make `RawEngine` "inherit" another existing `RawEngine` to avoid needing to create fresh ones every time?

Not really... can't do that in Rust.

> Or perhaps you can have the methods in `Engine` create a `ScopedEngine` and delegate to it? Except for the methods that needs to mutate the `Engine`.

Delegation also no...

**Comment by alvinhochun** [comment]
Surely something should be doable? Perhaps some refactoring may help?

**Comment by schungx** [comment]
I am thinking.

I tried refactoring to add lifetimes to `Engine` but then it seems to change thirty million lines of code and there are many references with different lifetimes and the borrow checker basically puked the whole thing back to me...

**Comment by schungx** [comment]
Closing this for now, as it probably won't change any time soon.
