### ISSUE TITLE
An issue with dot operator associativity

### ISSUE THREAD

**Issue by Eliah-Lakhin** [jonathandturner/rhai#179]
Consider we have a Rust builder pattern:

```rust
struct Builder {..}

impl Builder {
    set_x(mut self, x: f64) -> Self  { self.x = x; self }
    set_y(mut self, y: f64) -> Self  { self.y = y; self }
}
```

It's typical use case in Rust would look like this:

```rust
Builder::new().set_x(100.0).set_y(200.0).set_x(50.0);
```

In rhai, however if we export builder's functions with `lib.set_fn_2("set_x", |mut builder: Builder, x: f64| Ok(builder.set_x(f64)))` it will only work for a limited number of call-chain invocations:

```
  new_builder() // returns an instance of Builder. So far so good.
    .set_x(100.0) // still good. It accepts first argument by value and returning a value.
    .set_y(200.0) // if we add third step the entire chain fails.
```

So, it seems like Rhai has inconsistent behavior in call-chain interpretation when the chain has more than two steps.

**Comment by Eliah-Lakhin** [comment]
After further experiments I figured out that the bug lays down this issue is wrong `.`(dot) operator precedence. Seems like the precedence is right-associative means that if I put explicit parenthesis it works well:

```
  ( new_builder()
    .set_x(100.0) ).set_y(200.0)
```

@schungx Can you fix the dot operator precedence associativity, please? Right-associativity is very unusual and unintuitive for most of the programming languages.

**Comment by schungx** [comment]
Hhhmmm... let me check it out.

**Comment by schungx** [comment]
OK.  It is now officially a bug.  Thanks for flushing it out!

Somehow nobody actually tried to build a fluent interface in Rhai before.

**Comment by schungx** [comment]
It is now fixed.  Can you pull from the latest outstanding PR and test it?

**Comment by Eliah-Lakhin** [comment]
@schungx Pulled from you master branch. Seem to be working now. Thank you very much!
