### ISSUE TITLE
Etymology of the name "Rhai"?

### ISSUE THREAD

**Issue by vi** [jonathandturner/rhai#181]
I expect README or the Book to contain why the language is named "Rhai".

"R" is probably "Rust". Is "h" for "hosted"? "ai" - AST interpreter?

Anyway, a FAQ section somewhere may be nice.

**Comment by schungx** [comment]
This is probably a good question for @jonathandturner  who first built the language!

I suppose it started from [ChaiScript](http://chaiscript.com/) and because it is coded in Rust, it became Rhai...

**Comment by schungx** [comment]
> Anyway, a FAQ section somewhere may be nice.

Yes, I intend to do one - when I have some time!

**Comment by luciusmagn** [comment]
And Rhai is also `some` in Irish haha

**Comment by schungx** [comment]
I came across of copy of `Catcher in the Rye` recently and designed a logo, for laughs:

![rhai_logo](https://user-images.githubusercontent.com/661318/87165050-2d8d3f00-c2fc-11ea-9091-a3e4dbd7cbd7.png)

**Comment by jonathandturner** [comment]
@schungx has it. [ChaiScript](http://chaiscript.com/) is the language I did with my cousin. Then, when I first started learning Rust, I ported some of those same ideas. The C from Chai became the R in Rust, hence Rhai.

**Comment by vi** [comment]
So why "ChaiScript" named so? C++-hosted AST interpreter script?

**Comment by jonathandturner** [comment]
@vi - nothing quite so clever, I'm afraid. It was more thinking of scripting languages, and then making a play on JavaScript. Java being a kind of hot beverage, we tried to come up with scripts named after other hot beverages.

**Comment by schungx** [comment]
Since we're all at it, any chance to think of a nice logo and/or mascot for Rhai?

**Comment by schungx** [comment]
> And Rhai is also `some` in Irish haha

So... Rhai None = `Some(None)`?

**Comment by vi** [comment]
> Since we're all at it, any chance to think of a nice logo and/or mascot for Rhai?

Isn't [the picture you posted above](https://github.com/jonathandturner/rhai/issues/181#issuecomment-656703755) the logo of Rhai?

**Comment by schungx** [comment]
> Isn't [the picture you posted above](https://github.com/jonathandturner/rhai/issues/181#issuecomment-656703755) the logo of Rhai?

Nah, it is only for laughs.  Not official.

**Comment by vi** [comment]
> Nah, it is only for laughs. Not official.

It looks like a reasonable logo of some thing. The only missing thing is placement in the book, README and on the site.
