### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by felixrabe** [jonathandturner/rhai#193]
Hi - LICENSE.txt contains only Apache 2.0, but Cargo.toml says `license = "MIT OR Apache-2.0"`. Please clarify.

**Comment by schungx** [comment]
Well, I guess `LICENSE.txt` was generated by Github when it complained that the repo doesn't have a license, and so I just picked Apache.  Probably a good idea to also paste in a copy of MIT...

From my observations, it seems `MIT or Apache` is a pretty popular licensing terms for open source libraries.  @jonathandturner  what is your take on this?

FWIW...  I am not sure I know the difference between MIT and Apache...

**Comment by felixrabe** [comment]
Pull request incoming.

**Comment by jonathandturner** [comment]
@schungx either one is fine with me
