### ISSUE TITLE
Support more number literal types, including floating point

### ISSUE THREAD

**Issue by jonathandturner** [jonathandturner/rhai#2]
Currently, you can only create i32 literals.  Shouldn't be hard to add support for other integer and float literals.

**Comment by rustysec** [comment]
Is this satisfied by #28? Or should other variants also be available? I will take this on if we have requirements.

**Comment by luciusmagn** [comment]
The requirement is that we should be able to specify whether we want unsigned integers, signed integers, different sizes - 8, 16, 32, 64 bits, but also try to figure out proper type without specifying in a way that doesn't get in the way of the user and allows seamless interaction between these types.

**Comment by schungx** [comment]
It'll be easy to extend the parser to support tagging a type name to a numeric literal.  However, once you have it, other than using it to support calling into external functions that take `usize` or `u16` etc., it really isn't very useful...

```rust
let a = 10_i64;    // i64
let b = 32_i8;     // u8
let x = a + b;     // <- Do you allow this?

let x = a + (b as i64);    // <- or this?
```
