### ISSUE TITLE
Is it dead?

### ISSUE THREAD

**Issue by minecrawler** [jonathandturner/rhai#20]
The last commit was nearly a year ago. I really like the Rhai syntax and the way to use it from Rust, but I don't want to use a dead project...

**Comment by jonathandturner** [comment]
Sadly, it's definitely in a "deep sleep" mode.  I have some ideas around how to make it easier to use and support more function types, but I unfortunately haven't had time to come back to this project and implement them.

**Comment by minecrawler** [comment]
Thank you for the quick reply! That's very sad to hear. I will definitely keep Rhai in my watch list, as I don't have time for yet another project at the moment. I really hope to see it "wake up" again in the future :)
