### ISSUE TITLE
unicode-xid support for identifiers.

### ISSUE THREAD

**Issue by ekicyou** [jonathandturner/rhai#204]
I'm looking for a scripting language with an identifier of unicode-xid because I'm considering DSL for Japanese processing. 

Do you have any plans to respond?
Or do you accept PR using "unicode-xid" crate?

**Comment by schungx** [comment]
There doesn't seem to be anything stopping an identifier from being extended to non-ASCII characters...

However, I am not sure if this will be a significant need, and it pulls in an additional crate.

Perhaps under a feature flag...  

Would you like to open a PR and put it under a feature such as `unicode-xid-ident`?

**Comment by ekicyou** [comment]
Thank you, consider using feature flag.
> We avoid alphabet limitation because DSL is the main extension point for scripts.

**Comment by schungx** [comment]
BTW, just out of curiosity, why do you need identifiers in non-ASCII letters?  That would make it very unusual as a programming language...

**Comment by ekicyou** [comment]
I'm making a DSL that describes game scenarios.Like MarkDown, it's a set of grammar from the beginning.
The goal is to define programmatic behavior for specific verbs and nouns in a document.
'rhai' is a Unicode ready and made issue because the xid extension looked easier. Object mapping is not direct to this purpose.

**Comment by schungx** [comment]
Ah OK.  Glad if you'd want to work on a PR.
