### ISSUE TITLE
[BUG] parse_json function doesn't work with an array of objects

### ISSUE THREAD

**Issue by TimUntersberger** [jonathandturner/rhai#219]
**This works**
```rust
let str = r#"{
    "test": ["str"]
}"#;
let map = engine.parse_json(str, true);
```

**This doesnt work**
```rust
let str = r#"{
    "test": [{ "str": "str" }]
}"#;
let map = engine.parse_json(str, true);
```

**Error**
```
Err(
    ErrorParsing(
        BadInput(
            "Unexpected \'{\'",
        ),
        2:34,
    ),
)
```

I looked a bit at the source code and it looks like you trim the string and then prepend a `#`. This assumes that nested objects start with a `#` in JSON, which is not correct. I assume that this is a problem with nested objects overall and not only an array of objects.

**Comment by schungx** [comment]
Hhhmmm... you're right.  This is a bug.  Yes, you need to append `#` in front of any object hash inside the JSON.

For now, you can use `serde` to deserialize JSON into an object map.  I am not sure this will be easy to fix...

Maybe I need to write a note in the documentation saying: Warning nested objects.

**Comment by schungx** [comment]
Alternatively, if you have no `{` in strings, you can replace all `{` with `#{`, except for the first one (the `#` will be added).  That should cause it to parse correctly...

**Comment by schungx** [comment]
The latest version in master will have support for a leading `#{` for `Engine::parse_json`.  This is convenient if you'd just replace all `{` with `#{`.

Closing this for now.
