### ISSUE TITLE
Unable to compile stable toolchain on Windows

### ISSUE THREAD

**Issue by xmclark** [jonathandturner/rhai#220]
I could not compile for the msvc target. I did not find any documentation suggesting Rhai does not build on stable windows. I did find docs about requiring nightly for `no_std`. It compiles successfully if I use the nightly toolchain.

Received many errors of the type:
```
error: attributes are not yet allowed on `if` expressions.
```

To reproduce, create a new project with rhai in dependencies. Do a cargo build --release.

```toml
[dependencies]
rhai = "0.18.1"
```

![image](https://user-images.githubusercontent.com/1364747/90474415-13eccd80-e0da-11ea-8e21-e87f1836439a.png)

**Comment by schungx** [comment]
It does build on Windows MSVC.  I believe you don't have the latest version of compiler.  I believe you'll need `1.45` and up.

Attributes on `if` expressions are allowed in recent versions of Rust.

**Comment by schungx** [comment]
Do you have this resolved?  If so, we can close this issue.

**Comment by xmclark** [comment]
Yeah that works! Thanks.
