### ISSUE TITLE
Calling a function in the same module

### ISSUE THREAD

**Issue by nigelgbanks** [jonathandturner/rhai#231]
The following doesn't seem possible, unless I'm missing something.

**test.rhai**
```rust
fn foo() {
  debug("called foo");
}

fn bar() {
  debug("called bar");
  foo(); // Can't call function in same module with out re-importing the module in the scope of this function.
}
```

**main.rhai**
```rust
import "test" as test;
test::bar();
```

The only workaround I've been able to find is to re-import the module in the module function.

**test.rhai**
```rust
fn foo() {
  debug("called foo");
}

fn bar() {
  import "test" as test;
  debug("called bar");
  test::foo(); // Can now call the function.
}
```

Which begs the question what's the point of private functions for modules if they could never be called? 

https://schungx.github.io/rhai/language/modules/export.html

**Comment by schungx** [comment]
> Which begs the question what's the point of private functions for modules if they could never be called?

Private functions in modules can be used to initialize the module.  Typically a module will run top-level code and at the end export a bunch of objects and functions.  That top-level code can freely call any function, private or public.

**Comment by nigelgbanks** [comment]
Thank you that make sense!.

**Comment by schungx** [comment]
> The only workaround I've been able to find is to re-import the module in the module function.

Another workaround is to have the function take a function pointer as parameter:

```rust
fn foo() {
  debug("called foo");
}

fn bar(callback) {
  debug("called bar");
  callback.call();
}

import "test" as test;

fn test_cb() {
    import "test" as test;
    test::foo();
}

test::bar(Fn("test_cb"));
```

**Comment by nigelgbanks** [comment]
If I always want to call the same function is there way to curry the exported function such that the callback is captured like a closure ?

**Comment by schungx** [comment]
```rust
test::bar(|| {
    import "test" as test;
    test::foo();
});
```

**Comment by schungx** [comment]
Remember, in Rhai, all functions are independent from each other.  They can be split apart, regrouped, gathered, diced up, and then repackaged.  Therefore, functions cannot implicitly depend on each other because you never know whether the other function will exist.

**Comment by nigelgbanks** [comment]
I suppose my use case doesn't fit so well basically I've written a tool that processes all the data in an existing application with the intent to migrate it to another. 

The source data varies for each user of the application so they the data is not homogeneous. My intention is to use rhai to allow the users of my tool to customise the migrated data taking into account their customisation and differences. That being said many will end up having a lot of the same code. I have many functions that are similar and would like to reduce the amount of rhai code written so that there isn't so much repetition within a single module that users could then import. Passing in all the functions as callbacks is a bit odd since the function will only ever call the single function and not vary.

Thank you very much for taking the time to answer my question. I'll continue to use rhai and just re-import the module in every function. So that it will be able to refer to functions internally.

**Comment by schungx** [comment]
If your functions are Rust-based, you can simply register them.  Then your users can use those functions whenever they want.

If your functions are Rhai-based, then yes it is going to require going through some hoops in order to cross-call functions.

**Comment by nigelgbanks** [comment]
Thanks again for answering my question!
