### ISSUE TITLE
Empty block

### ISSUE THREAD

**Issue by hkazu** [jonathandturner/rhai#233]
Hi, I'm little curious, in statement like:

`if 1==0 {
// Empty block...
} else {
    print("False");
}`

I've noticed that else block part is not executed. I could be wrong, but reporting here...Thanks.

**Comment by schungx** [comment]
I'm sure you'll find that everything following `//` is a comment...

Actually this is a syntax error - unmatched `{`.

But you're right, an if-statement with an empty `if` statement block has a bug.  I'll be fixed.

Thanks for raising this.

**Comment by schungx** [comment]
Pull from this repo.  The latest should now be fixed.  Thanks.
