### ISSUE TITLE
How do I do Callbacks in Rhai

### ISSUE THREAD

**Issue by Debmalya99** [jonathandturner/rhai#235]
Hi I just started using Rhai. So far a great language to suit my needs. 
**I am trying to do callbacks like I do in Python.**
`print("Hi");`
`fn make_double(x){`
 ` return 2*x`
`}`

`fn callback_test(num,func){`
 ` print(func(num))`
`}`

`callback_test(32,make_double);`

But this does not work. Gives the following error:

`Hi
thread 'main' panicked at 'Failed to evaluate: ErrorVariableNotFound("make_double", Position { line: 10, pos: 18 })', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
`

**Version of Rhai used: 0.10.0 from crates.io**

Can anyone please help me solve this?

**Comment by schungx** [comment]
This is not Python.  The `make_double` in your last statement is a variable called `make_double`, not the function.

Try:

```rust
print("Hi");

fn make_double(x){ 2*x }

fn callback_test(num,func){
    print(func.call(num))
}

callback_test(32, Fn("make_double"));
```

**Comment by Debmalya99** [comment]
Thank you. I will try this.
