### ISSUE TITLE
arrays don't support pushing custom types

### ISSUE THREAD

**Issue by SuperCuber** [jonathandturner/rhai#237]
Not sure if this is intended behavior, but if you do in rhai:
```rust
let arr = [/* some array */];
arr.push(obj);
```
where `obj` is a registered custom type, the following error happens: `Function not found: 'push (array, your_custom_type)'`.

However, it's possible to handle the array in every other way (including constructing `[obj]` directly).

A possible workaround currently is
```rust
let arr = [/* some array*/];
arr = arr + [obj];
```

I suggest blanket implementing `push(array, T)`.

**Comment by schungx** [comment]
This is the current behavior.  You must manually implement `push(array, T)`.

> I suggest blanket implementing `push(array, T)`.

There are currently no plans for auto implementation of custom types simply because there would be many functions that need to be handled this way.  Probably `print` should be implemented first...

> A possible workaround currently is

You can also do: `arr += obj;`

**Comment by SuperCuber** [comment]
`arr += obj;` doesn't work, however `arr += [obj];` does. I assume that's what you meant.

> what happens if the user overrides array.push?

I think that's a bit of a narrow use case but I see what you're saying, especially in the more general case.

Regardless, since you're documenting how to implement [printing](https://schungx.github.io/rhai/rust/print-custom.html), I think it's worth mentioning this behavior in the docs as well (and maybe other similar cases that I haven't encountered)

**Comment by SuperCuber** [comment]
Additionally, I see that `obj in array_of_obj` doesn't work correctly (always returns false) even though `PartialEq` is derived on `obj`. I assume there's a similar situation where I need to overload the `== (my_type, array)` operator for it to work?

Maybe a page of "how to make your type work with arrays/maps fully" is a good idea

**Comment by schungx** [comment]
> `arr += obj;` doesn't work, however `arr += [obj];` does. I assume that's what you meant.

Ah, yes.  Sorry.  You're right.

**Comment by schungx** [comment]
> 
> 
> Additionally, I see that `obj in array_of_obj` doesn't work correctly (always returns false) even though `PartialEq` is derived on `obj`. I assume there's a similar situation where I need to overload the `== (my_type, my_type)` operator for it to work?
> 
> Maybe a page of "how to make your type work with arrays/maps fully" is a good idea

Yes, `in` internally calls `==` to compare two items.

**Comment by SuperCuber** [comment]
This is how I register `==` for `MyType: PartialEq` btw, just to save you the headache of trying to `register_fn("==", MyType::eq)`
```rust
engine.register_fn("==", |a: &mut MyType, b: MyType| a==&b);
```

**Comment by schungx** [comment]
Actually, I think the last couple of lines in https://schungx.github.io/rhai/language/arrays.html already says `push` and `pad` must be implemented separately.

I'll put in instructions also on implementing `==` for `in`, and put in a link to it from the section on custom types.

**Comment by SuperCuber** [comment]
I'd put the custom push explanation before the examples.

Also, I see `==` when not implemented returns `false` instead of causing a "function not found" error.
Maybe it's possible for `push` to have a default implementation as well? Or are they different somehow?

**Comment by schungx** [comment]
> Or are they different somehow?

They are different.  `==` has a default _return value_ when the function is not found.  `push` would have a default _implementation_...

**Comment by SuperCuber** [comment]
I see. Maybe it's possible to extend the engine to support default implementations but not doing that is a completely valid choice as well.
