### ISSUE TITLE
Slightly misleading message when feeding an invalid type into a custom setter

### ISSUE THREAD

**Issue by SuperCuber** [jonathandturner/rhai#245]
In the code [here](https://github.com/jonathandturner/rhai/blob/1d77e3e174859969a952646dcba8cb5227197f0e/src/fn_call.rs#L299), this case can also happen when the right hand value of the assignment is of the wrong type.

The error message should probably reflect that as a possibility.

**Comment by schungx** [comment]
I'll change it to: `Property 'prop' for MyType either doesn't exist, is read-only, or the value provided is of the wrong type.`
