### ISSUE TITLE
Not informative panic message in a failed `.cast()`

### ISSUE THREAD

**Issue by SuperCuber** [jonathandturner/rhai#246]
When a `Dynamic::cast` fails it results in a panic: 
```thread <unnamed> panicked at 'called Option::unwrap() on a `None` value'```
And the location of the panic is given inside the `rhai` crate. Instead, I think it should use `panic!()` with a better error message - something like `called Dynamic::cast::<T>() with non-matching T` and maybe display both type names.

Relevant code: https://github.com/jonathandturner/rhai/blob/master/src/any.rs#L784

**Comment by schungx** [comment]
Yes, it would benefit with a better panic message.  I'll add it in.
