### ISSUE TITLE
Can no longer send functions between modules

### ISSUE THREAD

**Issue by SuperCuber** [jonathandturner/rhai#247]
After the changes in #241 , now you cannot send a function between two modules.
```rust
module.rhai:

fn test(action) {
    action();
}

main.rhai:

import "module" as module;
module::test(|| {print("test");});
```

Errors with `Function not found: 'anon$ef32cb20fe8c79d5 ()'`.

A similar error happens when using `Fn("")` syntax.
I assume this is because functions are resolved when they are called and not when they are created - maybe it's possible to change that?

Regarding expected behavior - I expect `Fn("fn_in_main")` to work *only* in `main.rhai` since that's where it's defined, but the *result* of that call to work anywhere it's passed

**Comment by schungx** [comment]
That's true...  the new default module system will run each function call in the module's private namespace.

The closure `|| { print(...); }` is actually an anonymous function defined in the global namespace.  `Fn(...)` only captures the _name_ of the function, and obviously it couldn't find it in the module's namespace.

It is possible to resolve, but at a significant speed penalty - we merge the global namespace with the module namespace before each function call.

**Comment by schungx** [comment]
It is possible to merge in anonymous functions (aka closures) before each call, and that seems to work fine (at a cost of cloning).

However, it doesn't work if the closure calls a function that's defined in main:

```rust
module.rhai:

fn test() { print("test!"); }

fn action(f) { f.call(); }

main.rhai:

fn foo() { print("foo!"); }

import "module" as m;
m::test(|| test());             // works
m::test(|| foo());             // 'foo' not found
```

This is quite counter-intuitive...

**Comment by SuperCuber** [comment]
I feel like all of these behaviors would be much easier to implement and understand if rhai was designed in a way where functions weren't independent but could access their environment freely... But maybe that's too late to change at this point and you just gotta hack around it now.

The way I'd try to implement it is that when the AST is being compiled or `eval_from_new`ed (I'm not sure about the difference) from the module's file, the function *calls* all get resolved at that point. Then, when the function gets passed somewhere, the function calls inside it still resolve to whatever they resolved to before. So I guess function names are not good enough for this - maybe all functions get unique ids that are visible everywhere? Or maybe you can do it with actual function pointers, although that might not work with closures...

Oh and gotta think what to do about imported functions from modules - if you're using that solution, now you gotta resolve those at compile-time as well which means compiling a module needs compiling its dependencies and that could get complex/slow... Hmm.

The system I'd love Rhai to mimic regarding visibility in modules is Python's module system - I think it just works really well.

**Comment by schungx** [comment]
> I feel like all of these behaviors would be much easier to implement and understand if rhai was designed in a way where functions weren't independent but could access their environment freely... But maybe that's too late to change at this point and you just gotta hack around it now.

Yes.  Again, Rhai doesn't implement a scope-chain for performance reasons.  That is a deliberate design limit.

> Then, when the function gets passed somewhere, the function calls inside it still resolve to whatever they resolved to before.

You need to copy the entire function definition around to do that.  Essentially, merging both namespaces (global and module) work in a similar manner.

> The system I'd love Rhai to mimic regarding visibility in modules is Python's module system - I think it just works really well.

Well, Rhai has different design goals...  Otherwise, why not just write in Python?

**Comment by schungx** [comment]
Actually I have implemented the merging and it seems to work well...  So I may make it the default behavior...

So now you get:

```rust
module.rhai:

fn test() { print("test!"); }

fn action(f) { f.call(); }

main.rhai:

fn foo() { print("foo!"); }

import "module" as m;
m::test(|| test());             // works
m::test(|| foo());             // also works
```

**Comment by SuperCuber** [comment]
> Why not just write in Python?

Python is harder to tightly integrate with Rust like Rhai can (calling functions both ways, with custom types), at least from a surface-level looking around.

> Seems to work well

Will this work for weird edge cases like a chain of 3+ modules with similar function names?

**Comment by schungx** [comment]
> Will this work for weird edge cases like a chain of 3+ modules with similar function names?

Each module function overwrites a function with same name in parent modules.  The bottom layer is the global namespace.  So that should work... by theory...

**Comment by schungx** [comment]
You can pull from https://github.com/schungx/rhai to test out the new functionality...

**Comment by schungx** [comment]
The new PR lands on the official repo, so you can now pull on that.

Closing this issue for now.
