### ISSUE TITLE
String in rhai::Map

### ISSUE THREAD

**Issue by d00z3l** [jonathandturner/rhai#250]
Hello,

I am having a problem retrieving string values from a rhai map. The type returned is `string` but it seems that the rhai engine doesn't see it as a string so I can't print and the comparison fails. What I am I doing wrong?

```rust
#[test]
fn test_rhai_map_string() {

    let mut engine = Engine::new();
    engine.on_print(|s|{
        println!("{}", s);
    });
    let ast = engine.compile(r#"
        let val = data["Dim1"];
        print(val.type_of());
        print(val);
        if data["Dim1"] == "A" {
            print("A");
        } else {
            print("B");
        }
        "#
    ).expect("failed");

    let mut data = rhai::Map::new();
    data.insert(ImmutableString::from("Dim1"), Dynamic::from("A"));
    data.insert(ImmutableString::from("Dim2"), Dynamic::from("B"));
    
    let mut scope = Scope::new();
    scope.push("data", data);

    engine.consume_ast_with_scope(&mut scope, &ast).expect("failed");

}
```

**Comment by schungx** [comment]
What is the output that you got?

**Comment by schungx** [comment]
`Dynamic::from("A")` is a _bad_ idea.  You really should use `Dynamic::from(String::from("A"))` or `String::from("A").into()`.

**Comment by schungx** [comment]
I've added `Dynamic::from(&str)` to construct a string based on a slice.  It'll go into the next version.

Thanks.

**Comment by d00z3l** [comment]
Hi @schungx,

Thanks, the output I get is that method `print(string)` doesn't exist, even though it clearly does so I assume there is a wrapper around that value that makes the type different. 

Thanks for the tip on the type, I will give it a try!

**Comment by d00z3l** [comment]
Yep, that works, thanks for the tip.
