### ISSUE TITLE
Question: Register function with functional parameters

### ISSUE THREAD

**Issue by Kaiser1989** [jonathandturner/rhai#258]
Usecase:
Users write scripts for manipulating time series. I evaluate the script to provide a new timeseries (over some timestamps).

Is there any chance to get something like this:

```rust
fn add(x: i64, y: i64) -> i64 {
    x + y
}
...
engine.register_fn("add", add);
```

done with functional parameters:

```rust
type TimeFunc = Box<dyn Fn(i64) -> f64>;    // function taking i64, returning f64
fn add(x: TimeFunc, y: TimeFunc) -> TimeFunc {
    Box::new(|t: i64| x(t) + y(t))
}
...
engine.register_fn("add", add);    //<---- the trait bound rhai::RegisterFn [...] is not satisfied
```
(The compiler complains about unsatisfied Traits).

I also tried to use rhai objects, but there i stuck implementing the body:
```rust
type TimeFunc2 = Box<dyn Func<(i64), f64, Output = f64>>;
fn add(x: TimeFunc2, y: TimeFunc2) -> TimeFunc2 {
    // ????
}
```

I know this can be done within the script easily:

```rhai
fn add(x, y) {
    |t| x.call(t) + y.call(t)
}
```

But providing predefined functions within the script feels wrong. Imagine, i have about 20 - 25 time depending functions i want to predefine and provide to the user.
First thought was implementing them in Rust, and adding them as "register_fn" to the engine.
Is it wrong (or bad performance) to write all those functions in script language, compile them and finally adding user's script?

Thanks

**Comment by schungx** [comment]
> (The compiler complains about unsatisfied Traits).

A function closure or a trait object is not `Clone` so it cannot be used as a parameter.  That's why the compiles doesn't like it.

You are requesting function composition, which is complicated because Rhai doesn't really have first-class functions.  Function pointers and closures are simply syntactic sugar...

**Comment by schungx** [comment]
> Is it wrong (or bad performance) to write all those functions in script language, compile them and finally adding user's script?

That's exactly how you'd want to do it, and Rhai makes it easy for you to do it this way.

First compile your base functions as an AST.  You can then merge that AST into your user script and all your functions will be available to the user script.

All script functions are shared and reference-counted, so merging is quick and cheap, as long as you don't have thousands of functions (each script using only one or two) and you don't do it in a tight loop.

This is especially true when the user script does _not_ define any functions.  In that case, the merging optimizes into a simple clone of the shared functions.

**Comment by schungx** [comment]
> But providing predefined functions within the script feels wrong.

It really depends on your needs.  It is not wrong to provide library functionality in script - if you want those functions to be easily changeable without recompiling.

Otherwise, you might want to simply register them in Rust (or create a custom package of your functions).

It is real easy to call a function pointer in Rust, and register a function with function pointer arguments.  Check the Book and you'll find examples.

**Comment by Kaiser1989** [comment]
Thank you so much. 
I will try that

**Comment by schungx** [comment]
Turns out the example in the Book isn't very easy to find.

Here it is:

```rust
use rhai::{Engine, Module, Dynamic, FnPtr};

let mut engine = Engine::new();

// Define Rust function in required low-level API signature
fn call_fn_ptr_with_value(engine: &Engine, lib: &Module, args: &mut [&mut Dynamic])
    -> Result<Dynamic, Box<EvalAltResult>>
{
    // 'args' is guaranteed to contain enough arguments of the correct types
    let fp = std::mem::take(args[1]).cast::<FnPtr>();       // 2nd argument - function pointer
    let value = args[2].clone();                            // 3rd argument - function argument
    let this_ptr = args.get_mut(0).unwrap();                // 1st argument - this pointer

    // Use 'FnPtr::call_dynamic' to call the function pointer.
    // Beware, private script-defined functions will not be found.
    fp.call_dynamic(engine, lib, Some(this_ptr), [value])
}

// Register a Rust function using the low-level API
engine.register_raw_fn("super_call",
    &[ // parameter types
        std::any::TypeId::of::<i64>(),
        std::any::TypeId::of::<FnPtr>(),
        std::any::TypeId::of::<i64>()
    ],
    call_fn_ptr_with_value
);
```
