### ISSUE TITLE
Tiny opt-in standard library

### ISSUE THREAD

**Issue by luciusmagn** [jonathandturner/rhai#27]
Implement a tiny standard library. Design is to be added

**Comment by rustysec** [comment]
Has this design been conceptualized yet? Curious to know what kinds of features you guys have in mind for 1.0.

**Comment by schungx** [comment]
https://github.com/jonathandturner/rhai/issues/98 has a basic set of utility functions split into a separate `builtin.rs` file.  More library functions can be added there in the future.

In order to opt-in, it may be necessary to split it into a feature.

**Comment by schungx** [comment]
Closed by https://github.com/jonathandturner/rhai/pull/104
