### ISSUE TITLE
The Discord chat link in the docs is invalid

### ISSUE THREAD

**Issue by dyaso** [jonathandturner/rhai#273]
Invite's expired or something.

https://github.com/jonathandturner/rhai/blob/master/doc/src/about/related.md

**Comment by schungx** [comment]
Ouch!  I'm new to this Discord thing...  I was wondering why nobody joined!

:-)

Do you know how I can get a link for everybody that doesn't expire?

**Comment by schungx** [comment]
How about this?

https://discord.com/channels/767611025456889857/

Is this the right thing?

**Comment by dyaso** [comment]
That works, thanks! Apparently the default invite links expire after a day, there's a small option at the bottom of the link creation dialogue box to extend the limit.

**Comment by schungx** [comment]
I'll update a new link with a new PR.
