### ISSUE TITLE
Allow functions to access global imports

### ISSUE THREAD

**Issue by TimUntersberger** [jonathandturner/rhai#277]
Splitting functionality up into multiple files is a bit annoying right now.

#### main.rhai
```
fn test1() {
  import "mod" as M;

  M::echo();
}

fn test2() {
  import "mod" as M;

  M::echo();
}
```

#### mod.rhai
```
fn echo() {
  print("Hello World");
}
```

Having to write the import statement twice is really ugly and a bit annoying to write. Is there a way to write the `main.rhai` file like this?

#### main.rhai
```
import "mod" as M;

fn test1() {
  M::echo();
}

fn test2() {
  M::echo();
}
```

Using the namespace merging feature makes this a bit more bearable, but requires you to scope your functions with prefixes.

Any ideas?

**Comment by schungx** [comment]
> Is there a way to write the `main.rhai` file like this?

Yes, originally it was like this (`import` statements carry through into functions).

However, it sort of breaks Rhai's fundamental design, which is decoupling functions - you can break functions apart and mix-'n-match them at will.  Each function, essentially, should be its own little universe, so the design changes into having to import in each function.  This keeps functions independent from each other.

There are pros and cons.  While being wordy to write, it is more flexible and less prone to breakage.  Also, it avoids a data-race situation where module variables are used in scripts while the modules are also passed into function calls.

**Comment by schungx** [comment]
A possible way to do this is to just have Rhai _copy_ these global import statements to the beginning of each function block, which means that functions actually carry these module imports with them wherever they go.  This may be beneficial when you break apart a function and add it to a fresh script, you don't have to worry about the module import is not in the new script.

I might implement it to see if it works well...

**Comment by TimUntersberger** [comment]
Do you think it would be possible to have variables that are defined at the top level just live until the end of the program life?

example
```
let test = 1;

fn modify_test() {
    test = test + 1;
}

modify_test();
modify_test();
modify_test();
modify_test();
modify_test();

print(test);
```

I don't know whether this would be problematic, but I don't really see a usecase where it would be important to have the toplevel variables garbage collected.

**Comment by TimUntersberger** [comment]
Also don't you kind of have a garbage collector already?

```
fn print_test() {
    let test = 1;
    test = test + 1;
    print(test);
}

print_test();
```

The variable test is gone after each function call right?

**Comment by TimUntersberger** [comment]
Sorry for spawning the thread. Just throwing out some ideas.

**Comment by TimUntersberger** [comment]
> because don't forget you can do this:

I didn't know you can do that. What is the usecase for this? This seems very unintuitive for an import statement. Is this just supposed to be aliasing?

**Comment by schungx** [comment]
> Do you think it would be possible to have variables that are defined at the top level just live until the end of the program life?

In order for a function to _peek_ outside its scope (in this case look into the global scope), you need a link to that scope, and you start having to "search down the scope chain".  Rhai avoids this by making functions fully encapsulated without any global access (in a sense similar to Rust).  Searching a scope chain is slow.

**Comment by schungx** [comment]
> Also don't you kind of have a garbage collector already?

Not really.  The variables are removed at the end of the scope.  It is deterministic.

**Comment by schungx** [comment]
> I didn't know you can do that. What is the usecase for this? This seems very unintuitive for an import statement. Is this just supposed to be aliasing?

Well, originally I did it because I can...

A possible use case is to dynamically load different versions of modules (think each module as a custom configuration script) based on some parameters, or user ID or something.

Therefore, loading modules in Rhai is dynamic.

**Comment by TimUntersberger** [comment]
I meant this part

```
let s = "he" + "llo";
import s as H;
```

Why can you import a local variable?

**Comment by schungx** [comment]
> Why can you import a local variable?

As long as that expression (it can even be a function call or any expression) evaluates to a string.

For example:

```rust
import "my_mod_" + (40 + 2) as M;   // = import "my_mod_42" as M;
```

**Comment by TimUntersberger** [comment]
> I can only reasonably copy all the import statements that have constant paths

This would be enough I think.

> As long as that expression (it can even be a function call or any expression) evaluates to a string.

Have you thought about seperating these two functionalities (static vs dynamic)? 

The way Javascript handles this is very nice:

* `import` keyword for static imports (meaning things you know at compile time)
* `import` function for dynamic imports

**Comment by schungx** [comment]
> The way Javascript handles this is very nice:
> 
>     * `import` keyword for static imports (meaning things you know at compile time)
> 
>     * `import` function for dynamic imports

Actually that sounds very nice indeed...  but how do I make a namespace alias for the function style import?

```rust
let H = import("hello");    // is H a variable or a namespace?

import("hello") as H;        // how about this?
```

**Comment by TimUntersberger** [comment]
```
let H = import("hello");
```

Is better I think.

What if the import statement returns a namespace? 

While we are at it: What is the reasoning behind having `import "..." as M` be a namespace and not a simple object?

**Comment by TimUntersberger** [comment]
If the `import` keyword can't also return an object, then introducing namespaces as a new primitive would be better.

**Comment by schungx** [comment]
> While we are at it: What is the reasoning behind having `import "..." as M` be a namespace and not a simple object?

I originally had it that an imported module is a valid value that can be stored in a variable.  Which would make this exact syntax possible.

However, it turns out to be quite inefficient, especially when we're handling module variables.  So it is changed to a namespace object that cannot be stored in a variable.

**Comment by TimUntersberger** [comment]
Then I guess having the `import` function return a namespace would be better, but then again having a namespace returned feels kind of weird. What would you prefer? Namespace or object?

**Comment by schungx** [comment]
> Namespace or object?

Right now, the implementation needs a namespace, which is sort of consistent because, in Rhai, symbols like namespaces and function names are specifically not variables.  Therefore you cannot do:

```rust
fn foo() {}

let x = foo;
x();
```

Function names are resolved distinctly from variables names.  Same with namespaces.

**Comment by TimUntersberger** [comment]
So I guess having the `M` in the bottom be a namespace would be good.

```
let M = import("module");

M::test();
```

Then the `import` keyword would be the static thing which enables the thing I asked in the beginning.

```
import "module" as M;

fn test() {
  M::test();
}
```

Another thing I just thought of: If you enable global namespacing, is it always enabled?

Example

```
import "test"; // all of the functions are included in the global namespace
import "test" as test; // global namespace doesn't get polluted
```

Or is it it always merging the namespaces?

**Comment by schungx** [comment]
> `import "test";`

Well... I cheated.  You cannot do this.  ;-)

You must provide an alias.

**Comment by schungx** [comment]
So I suppose under the following:

```rust
let M = import("module");     // M is NOT a variable
M::test();    // works
M = 42;     // error - variable 'M' not found
```

Is that intuitive enough for you?

As for global imports:

```rust
import "test" as M;
let N = import("test");

fn foo() {
    M::test();     // Works
    N::test();      // Module 'N' not found
}
```

**Comment by TimUntersberger** [comment]
What if M is a variable, but it contains a namespace? If you know what I mean. Maybe namespaces could be a new primitive? Or is this gonna have technical difficulties?

**Comment by schungx** [comment]
> Maybe namespaces could be a new primitive?

As I said, it was originally implemented as a new primitive which can be loaded into a variable.

However, it got into some messy conflicts with the borrow checker, so it was pulled out.

**Comment by TimUntersberger** [comment]
> Is that intuitive enough for you?

Yeah, I think we should go ahead with this. 👍

**Comment by schungx** [comment]
```rust
let N = import("test");
import("test") as N; 
```

which one of the above do you prefer?

Also, we need to be a little careful here otherwise the auto-importing may go out of hand, such as:

```rust
import "mod1" as mod1;
import "mod2" as mod2;
import "mod3" as mod3;
    :
    :
import "modN" as modN;

fn get_token() { 42 }            // function does not use any imports
                                           // but must import N modules!

fn calc(x) {                          // function uses only mod3 but must
    mod3::do_calc(x)           // import all N modules!
}
```

**Comment by TimUntersberger** [comment]
> which one of the above do you prefer?

I prefer the first one.

**Comment by schungx** [comment]
Good news!  PR https://github.com/jonathandturner/rhai/pull/281 allows functions to use global `import`'s.

I found a way to get around the borrow checker.

**Comment by schungx** [comment]
Now you can simply do:

```rust
import "mod" as M;

fn test1() {
  M::echo();
}

fn test2() {
  M::echo();
}
```

**Comment by TimUntersberger** [comment]
Thank you! I couldn't test it yet as I now have to fix some issues after using the latest from master.

I used to have save a `FnPtr` for callbacks and later call the ptr like this:

```
ptr.call_dynamic(engine, ast, None, []);
```

but now I need to pass it the native function context and I don't know how I should do this now?

Could you please give me some pointers?

**Comment by schungx** [comment]
Just create one from the engine and `AST`:

```rust
let context = (
    engine,
    &[ast.as_ref()]
).into();
ptr.call_dynamic(context, None, []);
```

**Comment by schungx** [comment]
This feature will become standard in the up-coming `0.19.5`.

To create a `NativeCallContext`, you can also use this:

```rust
let context = NativeCallContext::new(&engine, &[ast.as_ref()]);
```
