### ISSUE TITLE
floating point literals

### ISSUE THREAD

**Issue by luciusmagn** [jonathandturner/rhai#28]
Parse floating point numbers. Rhai already supports them, but has no way of actually creating them:
```rust
let x = 5.00001;
```

**Comment by rustysec** [comment]
submitted #38 for this using this syntax
```js
let x = f5_00001;
```

**Comment by rustysec** [comment]
based on @luciusmagn feedback, updated the syntax to 
```rust
let x = 5.0001;
```

**Comment by rustysec** [comment]
can probably close per #38

**Comment by luciusmagn** [comment]
Ah, yes
