### ISSUE TITLE
0.19.5 needs to be released

### ISSUE THREAD

**Issue by BrettMayson** [jonathandturner/rhai#282]
There is a bug in 0.19.4 that is preventing compilation, this seems to be known since there is a fix on master. The crate should be updated so people's builds can work again.

**Comment by schungx** [comment]
The compilation error only happens in rare situations when the user uses the `internals` feature, which few people use.

But yes, I agree we need to put out `0.19.5` soon, and yank `0.19.4` off.

**Comment by schungx** [comment]
@BrettMayson  if you'd like to check out the latest master, if you don't find any prob with it, I'd release it at `0.19.5`.

**Comment by BrettMayson** [comment]
I don't use a lot of internal features, but master built for me
