### ISSUE TITLE
Bug/Question on importing modules

### ISSUE THREAD

**Issue by TimUntersberger** [jonathandturner/rhai#284]
Lets assume we have the following structure

* index.rhai
* lib
  * common.rhai

Where the files have the following content

index.rhai
```
import "lib/common";

print("index");
```

lib/common.rhai
```
print("common");
```

Now if I do the following the program just freezes

```rust
let ast = engine.compile("<path to index.rhai>").unwrap();
Module::eval_ast_as_new(Scope::new(), &ast, engine).unwrap();
```

Any idea why this could happen?

**Comment by schungx** [comment]
I don't see the same result... It completes successfully on my computer.

Are you sure you don't have `import "common";` in your `common.rhai`?

**Comment by TimUntersberger** [comment]
Yeah. This example is very simplified, but the gist of my problem is, that everything works fine when I import at the top level, but as soon as I import something one level deep into the import stack the program freezes.

Oh I just realized that the example has one level less of depth.

### UPDATED

* index.rhai
* temp.rhai
* lib
  * common.rhai

Where the files have the following content

index.rhai
```
import "temp";

print("index");
```

temp.rhai
```
import "lib/common";

print("temp");
```

lib/common.rhai
```
print("common");
```

Now if I do the following the program just freezes

```rust
let ast = engine.compile("<path to index.rhai>").unwrap();
Module::eval_ast_as_new(Scope::new(), &ast, engine).unwrap();
```

**Comment by TimUntersberger** [comment]
Maybe an example with more domain context can help

<details>
<summary>config.nog</summary>

```
import "modes/resize";
import "keybindings";
import "rules";

bind "Alt+E" toggle_config("remove_task_bar");

bar #{
    font: "CaskaydiaCove NF",
    font_size: 18
};

workspace 1 #{
    text: "  "
};

workspace 2 #{
    text: "  ",
    monitor: 1
};

workspace 3 #{
    text: " 阮 "
};

workspace 4 #{
    text: " ﭮ "
};

update_channel "test" #{
    branch: "development"
};

set default_update_channel "test";

disable work_mode;
enable display_app_bar;
enable launch_on_startup;
enable multi_monitor;
enable remove_task_bar;
```

</details>

<details>
<summary>rules.nog</summary>

```
import "temp";

ignore "explorer.exe";
ignore "Taskmgr.exe";
ignore "SnippingTool.exe";

rule "firefox.exe" #{
    has_custom_titlebar: true,
    workspace_id: 2,
    firefox: true
};

rule "Discord.exe" #{
    has_custom_titlebar: true
};

rule "Spotify.exe" #{
    has_custom_titlebar: true
};

rule "chrome.exe" #{
    has_custom_titlebar: true,
    workspace_id: 2,
    chromium: true
};

rule "Code.exe" #{
    has_custom_titlebar: true
};
```

</details>

<details>
<summary>temp.nog</summary>

```
```

</details>

In this example there is a lot of custom syntax, like `rule`, `ignore`, ...

If I have the import statement in the `config.nog` file it works, but if I move it into `rules.nog` it freezes.

**Comment by TimUntersberger** [comment]
I just found out that the code in the `temp.nog` file gets executed and then it freezes.

**Comment by TimUntersberger** [comment]
Something that might also be important:

The module eval ast part is inside a custom module resolver.

<details>
<summary>moduler resolver source code</summary>

```rust
use std::{collections::HashMap, sync::Arc};

use parking_lot::{Mutex, RwLock};
use rhai::{EvalAltResult, Module, ModuleResolver, Scope, AST};

use crate::AppState;

pub struct PluginModuleResolver {
    state_arc: Arc<Mutex<AppState>>,
    cache: RwLock<HashMap<String, AST>>,
}

impl PluginModuleResolver {
    pub fn new(state_arc: Arc<Mutex<AppState>>) -> Self {
        Self {
            state_arc,
            cache: RwLock::new(HashMap::new()),
        }
    }
}

impl ModuleResolver for PluginModuleResolver {
    fn resolve(
        &self,
        engine: &rhai::Engine,
        path: &str,
        pos: rhai::Position,
    ) -> Result<rhai::Module, Box<rhai::EvalAltResult>> {
        println!("locking");
        let plugins = self.state_arc.lock().plugin_manager.plugins.clone();
        for plugin in plugins {
            let mut file_path = plugin.path.clone();
            file_path.push("plugin");
            file_path.push(path);
            file_path.set_extension("nog");

            if file_path.exists() {
                if let Some(ast) = self.cache.read().get(file_path.to_str().unwrap()) {
                    return Ok(
                        Module::eval_ast_as_new(Scope::new(), ast, engine).map_err(
                            |err| {
                                Box::new(EvalAltResult::ErrorInModule(
                                    file_path.to_str().unwrap().to_string(),
                                    err,
                                    pos,
                                ))
                            },
                        )?,
                    );
                } else {
                    let ast = engine.compile_file(file_path.clone()).map_err(|err| {
                        Box::new(EvalAltResult::ErrorInModule(
                            file_path.to_str().unwrap().to_string(),
                            err,
                            pos,
                        ))
                    })?;
                    println!("eval");
                    let mut module = Module::eval_ast_as_new(Scope::new(), &ast, engine)
                        .map_err(|err| {
                            Box::new(EvalAltResult::ErrorInModule(
                                file_path.to_str().unwrap().to_string(),
                                err,
                                pos,
                            ))
                        })?;
                    println!("after eval");

                    // TODO: This line causes a deadlock, but I don't know why?
                    // self.cache.write().insert(file_path.to_str().unwrap().to_string(), ast);

                    return Ok(module);
                }
            }
        }

        Err(Box::new(EvalAltResult::ErrorModuleNotFound(
            path.to_string(),
            pos,
        )))
    }
}
```

</details>

**Comment by TimUntersberger** [comment]
Also something I noticed while implementing my custom resolver is that you don't return a `ModuleNotFound` error when the module is not found in the [relative resolver](https://github.com/jonathandturner/rhai/blob/f58e1d368a7b67e55600ba92ea955df1cd38c18e/src/module/resolvers/file.rs#L140).

The `file_path` could be a path that doesn't exist, but you don't check before trying to compile the file at this path, which then results in a file not found error getting mapped into the `ErrorInModule` error. The `ErrorInModule` stops the resolving process, which can be annoying when having multiple resolver in a resolver collection (You need the relative resolver to be the last one).

**Comment by schungx** [comment]
What I found is actually a panic on interior mutability.  Not sure why your code hangs, but my code will panic when there are more than one level of import files.  I'll fix that and you can test it more...

As for the file_path mapping to `ErrorInModule`... I think I can trap the file-not-found error in `compile`...

**Comment by TimUntersberger** [comment]
> What I found is actually a panic on interior mutability

Nice!

> I think I can trap the file-not-found error in compile

Could you elaborate? Can't you just do something like I did in my custom resolver?

simplified
```rust
if file_path.exists() {
  ....
  return Ok(module);
} else {
  return Err(Box::new(EvalAltResult::ErrorModuleNotFound(
    path.to_string(),
    pos,
  )));
}
```

**Comment by schungx** [comment]
Well, I just trap `EvalAltResult::SystemError(_, err) if err.is::<std::io::Error>()` and converts it into `ErrorModuleNotFound`.

**Comment by schungx** [comment]
The fix has landed in the master repo.  Can you pull from the latest and test it out?

It also converts `io::Error` into `ErrorModuleNotFound`.

**Comment by TimUntersberger** [comment]
Using the latest from master I no longer encounter this issue, but noticed a different one.

Assuming you have the following setup

### Structure

* index.rhai
* html.rhai
* html
  * index.rhai


#### index.rhai

```
import "html" as html;

html::test();
```

#### html.rhai

```
import "html/index" as html;

print(html::x); // works

fn test() {
  print(html::x); //doesn't work
}
```


#### html/index.rhai

```
const x = 10;
export x;
```

This setup results in an error when calling the `test` function, because it can't find the variable `x` of the module `html` in `html.rhai`.

Also could it be possible to support the following syntax? 

```
export const x = 10; // or
export let x = 10; // or whatever else could be nice
```

This would simplify exporting constants a bit.

**Comment by schungx** [comment]
Hhhmmm... strange... it works for me, both outside and inside the function.

> Also could it be possible to support the following syntax?

Possibly, but the variable cannot be renamed in such a syntax.

**Comment by schungx** [comment]
> `export const x = 10; // or`
> `export let x = 10; // or whatever else could be nice`

Turns out to be quite easy.  This new feature is now added.  Pull from the latest master to try it out.

**Comment by schungx** [comment]
> This setup results in an error when calling the test function, because it can't find the variable x of the module html in html.rhai.

I just realize that you have three levels of indirection here.  This is the correct behavior because:

`html/index.rhai`: `x`
`html.rhai`: `html::x`
`index.rhai`: `html::html::x`

In other words, the module does not encapsulate imported namespaces, only functions.  I'll fix that.

**Comment by schungx** [comment]
Again, turns out to be a relatively simple fix.

Pull from the latest master to test out.  Your last example should work now.

**Comment by TimUntersberger** [comment]
Works for me 👍

**Comment by schungx** [comment]
OK, `0.19.5` coming out.  Closing this.  Feel free to open up a new issue if there is still a problem.
