### ISSUE TITLE
How to use for example std::ops::Add instances without redefining + 

### ISSUE THREAD

**Issue by JPMoresmau** [jonathandturner/rhai#286]
Hello, I have a type called CellValue. This type implement std::ops::Add so + works in Rust code. If I try a script that does the same thing, I get `Err(ErrorFunctionNotFound("+ (tablr_lib::types::CellValue, tablr_lib::types::CellValue)", 1:4))`. However, if I define this simple function:
```
fn add_v(cv1: CellValue, cv2: CellValue) -> CellValue{
        return cv1+cv2;
    }
```
and register it via `engine.register_fn("+", add_v);`, the script works. Is there a way to avoid that step and have code using the Add implementation automagically?

Thanks!

**Comment by schungx** [comment]
Not easily, because Rhai really doesn't know that `CellValue` implements `Add`.  You'll need to wait until specialization lands in Rust, otherwise there is no simple way to auto-register the `+` operator with a type that is `Add`.

And the combinations of traits will get too many too quickly.

**Comment by schungx** [comment]
It would be nice if Rust has the following:

```rust
if implements!(T, Add) {
    // here T: Add
    return v1 + v2;
}
```

But alas it doesn't...

**Comment by schungx** [comment]
Closing this for now.  Short of being able to run specialized code based on the traits a type implements, I don't think we can get any shorter than this:

```rust
engine.register_fn("+", |v1: CellValue, v2: CellValue} v1 + v2);
```
