### ISSUE TITLE
Support more control structures

### ISSUE THREAD

**Issue by jonathandturner** [jonathandturner/rhai#3]
Would be nice to have a for loop and/or a for..in.. loop.  Right now the control structure story in Rhai is a bit thin, and before 1.0 it'd be nice to fill it out.

**Comment by tiberiusferreira** [comment]
Hello, thanks for this project! 

Is there support for 
```
if cond1{
}else if cond2{

}else{
}
``` 
or is it part of the roadmap?  I couldn't get it to work.

**Comment by jonathandturner** [comment]
That may not work yet, but in theory it shouldn't be too bad to add (though it's been a while since I worked on the parser). If you want to try adding it, I'd be happy to review the PR

**Comment by schungx** [comment]
> Is there support for
> 
> ```
> if cond1{
> }else if cond2{
> 
> }else{
> }
> ```

I'll see if it is easy to add in...

**Comment by schungx** [comment]
Turns out this is remarkable easy to ask.  Too all of 5 minutes...

Will be lumped into PR https://github.com/jonathandturner/rhai/pull/98.
