### ISSUE TITLE
Decide on increment/decrement (++/--) operators

### ISSUE THREAD

**Issue by luciusmagn** [jonathandturner/rhai#30]
++ and -- are tricky. Rust doesn't have them. Should Rhai?

**Comment by rustysec** [comment]
i think `+=` could be overloaded for more types than just numeric.
```rust
let x = 1;
x += 1;
```
but also
```rust
let s = "this is a ";
s += "test";
``` 
kind of semantics.

**Comment by luciusmagn** [comment]
Sounds like a great idea!

**Comment by rustysec** [comment]
should this get closed per #40? or wait for more testing and use cases?

**Comment by luciusmagn** [comment]
The stuff you implemented is awesome, but the main topic here are the `++` and `--` operators and whether they should be present at all in Rhai and if yes, how should they behave and where would they be valid. It is a trickly thing in regards to rustic safety

You implemented two of the compound assignment operators, which are tracked in #35

**Comment by rustysec** [comment]
aha! I'm following the distinction now, thanks for clarifying. I will take a look at the rest of #35 and leave this alone for now.
