### ISSUE TITLE
no `Locked` in `fn_native`

### ISSUE THREAD

**Issue by GopherJ** [jonathandturner/rhai#300]
![image](https://user-images.githubusercontent.com/33961674/100455907-cbbd4e00-30bf-11eb-9de1-069ea23b9451.png)

**Comment by GopherJ** [comment]
I tried to upgrade to rhai@0.19.6 but it gives an error

**Comment by GopherJ** [comment]
then I tried to add the feature `internals` to see if it solves this issue but I got another error

![image](https://user-images.githubusercontent.com/33961674/100456091-16d76100-30c0-11eb-8a6c-3c6813ef6da5.png)

**Comment by schungx** [comment]
I think your particular combination of feature flags happen to hit on a case that I didn't test for.

I'll fix those, but in the meantime, perhaps you can upgrade to a lower version.

**Comment by schungx** [comment]
This is now fixed in the latest master.  It'll go live in `0.19.7`.
