### ISSUE TITLE
Initial value as an argument in reduce

### ISSUE THREAD

**Issue by sunng87** [jonathandturner/rhai#302]
In the current implementation of `reduce`, we have to check if `sum` is empty for the initial value. It will be better the initial value is provided as an argument to `reduce`. This will make it clear and easy to understand and write the accumulation function

**Comment by schungx** [comment]
There is a version of `reduce` which takes a closure providing the initial value.  We cannot just register a function that takes an initial value because the type of the initial value is not determined.

**Comment by schungx** [comment]
https://schungx.github.io/rhai/language/arrays.html?highlight=reduce#built-in-functions

Check out the second optional parameter for `reduce`.
