### ISSUE TITLE
Provide look-ahead for custom parsers

### ISSUE THREAD

**Issue by pavlukivan** [jonathandturner/rhai#308]
An example use case: a series of statements in `{}` separated by `,`: `syntax_key { a, b, c, d }`. As far as I can tell, currently you can only do that if you force user to include some additional info in the last statement to specify that it's the last one.

As an alternative, rust macro-style pattern matching can be added, but it's naturally more complex to implement.

In the first place, it seems weird to me that parsers only have access to the symbols they already requested, as opposed to being able to parse whatever.

**Comment by schungx** [comment]
Not really, if you end with a `}`.  You can use `Engine::register_custom_syntax_raw` to register a parser, which keeps parsing `$expr$` and `,` until you receive a `}`.

**Comment by schungx** [comment]
> In the first place, it seems weird to me that parsers only have access to the symbols they already requested, as opposed to being able to parse whatever.

The parser has access to the symbols already parsed, and it tells the engine what is the next symbol expected.

That's the basic idea of a recursive-descent parser.

**Comment by schungx** [comment]
Yes, you cannot.  You need a _look-ahead_ in order to do that for a recursive-descent parser.

Rhai's custom syntax doesn't provide a look-ahead token yet..., so it is really LL(0) instead of LL(1).

To solve your problem, for variable-length parsing, you'd need a look-ahead.  I can probably add that to Rhai...

**Comment by schungx** [comment]
@pavlukivan   Turns out look-ahead is dead simple to provide.  It is now in https://github.com/jonathandturner/rhai/pull/309

You can pull from this master to try it out.

Thanks for your great idea!

**Comment by pavlukivan** [comment]
Thanks for the quick resolution!

**Comment by schungx** [comment]
Please test it out and see if there are any problems!

**Comment by pavlukivan** [comment]
This isn't an issue with the look-ahead specifically, but I'm not sure what's the problem with this code:

```rs
engine.register_custom_syntax_raw(
    "test",
    |stream, token| {
        match (stream.len(), token) {
            (1, _) => Ok(Some("$ident$".into())),
            (2, _) => Ok(Some("{".into())),
            (x, "}") if x % 4 >= 2 => Ok(None), // } after , or last ident
            (x, _) if x % 4 == 3 => Ok(Some("$ident$".into())),
            (x, _) if x % 4 == 0 => Ok(Some(":".into())),
            (x, _) if x % 4 == 1 => Ok(Some("$ident$".into())),
            (x, _) if x % 4 == 2 => Ok(Some(",".into())),
            _ => todo!(),
        }
    },
    0,
    |_, _| { Ok(Dynamic::UNIT) },
);
engine.eval::<()>("test { a: b, }").unwrap();
```
When running, it panics with `ErrorParsing(VariableExpected, 1:6)`

**Comment by schungx** [comment]
`(1, _) => Ok(Some("$ident$".into())),`

You are expecting an identifier when there is one symbol already parsed.  Obviously the one symbol is `test`, so the next token actually should be `{`, not an identifier.

**Comment by pavlukivan** [comment]
I changed the eval to `test a { a: b, }` and the error is now `called `Result::unwrap()` on an `Err` value: ErrorParsing(MissingToken(";", "to terminate this statement"), 1:16)'`

**Comment by schungx** [comment]
Of course, this is a statement.  You'll need to terminate it with `;`, even though it may look like it doesn't because it ends with `}`.

**Comment by pavlukivan** [comment]
It has the same error even when I add a ; after }

**Comment by schungx** [comment]
In that case, you're missing one token.  When the look ahead is `}`, you need to return `Some("}".into())` in order to _eat_ it.  Essentially you're saying the next symbol should be `}` and so please go ahead and match it.

Otherwise, if you return `None`, Rhai expects the custom statement to terminate and so is looking for a `;`, but it see a `}`.

**Comment by pavlukivan** [comment]
I see, that's a little counter-intuitive but it works now, thanks!

**Comment by schungx** [comment]
Yes, I'd probably need to make the write-up clearer.  Essentially, the parsing function returns the _next_ symbol expected.  The fact that we added a look-ahead and it happens to be, obviously, the _next_ symbol is a coincident.  It still has to match it (or the parser can fail, of course, returning another expected symbol).

**Comment by pavlukivan** [comment]
I meant the examples don't return `Some(None)` at the `;`, they return it earlier

**Comment by schungx** [comment]
Yes.  There is no need to match the `;` symbol.  It is handled automatically as a terminator for a statement.

**Comment by pavlukivan** [comment]
Ah, I see, so basically there's no need to return `Ok(None)` at all. What is it used for then?

**Comment by schungx** [comment]
You'll need to return `Ok(None)` at the very end when there is _no more symbols_ expected.  This means you return it when you have already parsed past `}`.

Rhai will continue to parse your custom syntax until `Ok(None)` is received.

**Comment by schungx** [comment]
Well, actually a custom syntax defines an _expression_, so you can use it anywhere you can use expressions.

Remember that a lone expression is also a statement, if you terminate it with `;`.

So if you want a statement, you'd need the `;`.

**Comment by pavlukivan** [comment]
Ah, thanks, I understand it now (though the `,` is already optional)
