### ISSUE TITLE
Ranges, rustic for loop

### ISSUE THREAD

**Issue by luciusmagn** [jonathandturner/rhai#31]
Implement ranges and a `for` loop like the one in Rust:
```rust
for i in 0..10 {
    print(i);
}

let x = 1..5;
```

**Comment by stevedonovan** [comment]
This would be very cool, but it's a special case of needing iterator support.

The for-loop syntax that occurred to me was inspired by other languages:

```rust
let a = ["one","two","three"];
for (s in a) {
   print(s);
}
```

Which is consistent with the current style for `if` statements.

**Comment by luciusmagn** [comment]
We try to mimic Rust wherever possible, so probably the syntax you'd find
in Rhai would be without the parenthesis. I do agree that we would need
iterators for this, hence why it's marked as a 1.0+ feature

2018-04-04 9:47 GMT+02:00 Steve J Donovan <notifications@github.com>:

**Comment by stevedonovan** [comment]
That makes sense - but then (to be consistent) it should be `if a > 0 {....}` as well. The grammar requires that the controlled statement is a block anyway, and so the parens are redundant (as we know and love)

**Comment by luciusmagn** [comment]
It already is that way. Maybe some legacy Rhai code has the parens, but
they are optional. I will review it when I get home

2018-04-04 11:25 GMT+02:00 Steve J Donovan <notifications@github.com>:

**Comment by cedric-h** [comment]
Not having this make Rhai very difficult to use.

**Comment by schungx** [comment]
PR https://github.com/jonathandturner/rhai/pull/98 adds iterators and `for` loops although there is no special range syntax, but uses a built-in `range` function instead.
