### ISSUE TITLE
Scope no longer implements Clone 

### ISSUE THREAD

**Issue by timfish** [jonathandturner/rhai#314]
Just updated to 0.19.8 and `Scope` no longer implements `Clone`. 

What this intensional?

**Comment by schungx** [comment]
It was removed a while ago because Scope is quite expensive to clone.  However, there is nothing preventing it from implementing `Clone`.  I'll add it back.

Why would you need to clone a Scope?

**Comment by timfish** [comment]
I calculate constants and add them to a scope. I then want to re-use a single engine and that scope for multiple isolated evaluations. By isolated, I mean each evaluation should start with the same original, unmodified scope. 

As every elevation can potentially modify the scope, the only way I can pass the same unmodified scope to every call of `eval_expression_with_scope` is to either clone it or create it from scratch again.

I assumed the clone would not be particularly cheap (ie. a full memory copy) but it shows the intent well and is a lot less lines of code than creating the scope again from scratch!

**Comment by timfish** [comment]
Ah, actually worked out I can solve this by `rewind` the scope. 

I would however leave `Clone` around on types wherever possible as it makes prototyping easier. My assumption is always that `clone()` is expensive but it's often the quickest way to get something working without having to consider lifetimes and mutability. 

I've never been using a library and wished that somebody had **not** implemented `Clone` but the inverse happens a lot!

**Comment by schungx** [comment]
I've already added it back and it'll show up on the next version.
