### ISSUE TITLE
cargo audit fix

### ISSUE THREAD

**Issue by smhmayboudi** [jonathandturner/rhai#321]
Would you please check your project with cargo audit and fix the issue. I am receiving a warning which I think you can solve it.

```bash
$ cargo audit

Crate:         rhai
Version:       0.19.8
Warning:       yanked
Dependency tree: 
rhai 0.19.8
└── casbin 2.0.5
```

**Comment by schungx** [comment]
Alright.  I shouldn't have yanked it so fast.  I'll unyank `0.19.8` for a while until later on.

It has a bug that causes errors when using closures (something that `casbin` doesn't need).  That's the reason for the  yank.
