### ISSUE TITLE
Return values from loops

### ISSUE THREAD

**Issue by luciusmagn** [jonathandturner/rhai#45]
A while ago, Rust introduced yet another amazing feature:
```rust
let x = loop {
    // complicated computations
    break 7;
};

assert_eq!(x, 7);
```

Would be cool if Rhai had it too. Maybe even for while & for (when it comes around)

**Comment by rustysec** [comment]
just an update, i'm extremely close to getting this working 100%

**Comment by luciusmagn** [comment]
Awesome! I am very close to working modules

2017-12-01 3:17 GMT+01:00 Russ <notifications@github.com>:

**Comment by rustysec** [comment]
so this works, but without introducing a `()` type into the script engine we can end up in some weird states. a loop {} may not always return something, there's no enforcement of consistency at this point. for instance a while loop like this:
```
let i = 0;
while i < 100 {
    if i == 50 { break true; }
    i+=<user input>;
}
```
depends on the user input to increment. if it never hits 50, the loop returns with () at the end which the engine doesn't really know how to gracefully handle. something like this is a simpler example:
```
> let x = while true == false { break 7 }
> print(x)
error: Function argument types do not match
```
while this works as expected:
```
> let x = while true == true { break 7 }
> print(x)
7
```
 If anyone has ideas _other_ than me implementing a () type, i'd love to hear them!

**Comment by schungx** [comment]
I'm wondering whether this is really necessary, as it is just as easy to write:

```
let x;

loop {
    // complicated computations
    x = 7;
    break;
};
```

This way, statements such as `while`, `loop`, `for` etc. do not need to be turned into valid expressions, avoiding some weird-looking scripts like `let x = while true == true { break 7 };`.

**Comment by schungx** [comment]
I'm closing this one unless that are new opinions.
