### ISSUE TITLE
Easy interface for calling Rhai functions from Rust

### ISSUE THREAD

**Issue by luciusmagn** [jonathandturner/rhai#46]
Calling Rust functions from Rhai is simple and easy, the other way around, not so much. The way I see it, we need a macro or two. Therefore, we need to:

1. Make `call_fn()` public (Already done)
2. Make a macro like call!() for calling Rhai functions
3. Document everything

However, this open to discussion, as there might be better ways to handle function calling from Rhai

**Comment by schungx** [comment]
The `call_fn` method is simplified in https://github.com/jonathandturner/rhai/pull/106
