### ISSUE TITLE
Separate tests into own files

### ISSUE THREAD

**Issue by luciusmagn** [jonathandturner/rhai#49]

**Comment by rustysec** [comment]
I can handle this if it's not underway already.

**Comment by luciusmagn** [comment]
It's not underway. At the moment, I am putting together first design draft of Rhai's stdlib, so I am not modifying any code at the moment. Feel free to proceed

**Comment by rustysec** [comment]
resolved by #50

**Comment by luciusmagn** [comment]
yup
