### ISSUE TITLE
Rhai is missing proper bound checking

### ISSUE THREAD

**Issue by torkleyy** [jonathandturner/rhai#58]
Accessing an element out of bounds shouldn't panic, but error.
I'll fix this after my current PR.

**Comment by stevedonovan** [comment]
+1 for this. `arr[index]` needs to become `arr.get(index)` and the result propagated as an error.

**Comment by schungx** [comment]
I've submitted a PR https://github.com/jonathandturner/rhai/pull/97 to fix this.
