### ISSUE TITLE
[RFC] Consider adding a `Value` type

### ISSUE THREAD

**Issue by torkleyy** [jonathandturner/rhai#60]
It might be worth adding an enum called `Value` and replace the current `Box<Any>` with that. That would allow us to have primitives and user data, while the former one is cheaper.

One related question is whether we want to encode basic types into the language. Currently, e.g. arrays are special cased while integers and floats are partially special cased (they don't define basic operators except through `register_default_lib`).

One motivation I see for that is that currently the integer type is `i64` which isn't very obvious at first. If you're trying to index an array by `u64`, that would fail. Looking at issues like #52 or #32 , having special types that we handle in another way would make these things easier.

A disadvantage of encoding basic types and operations into the language would be that it would make the language and / or the library more complex.

I am myself unsure which way to go here.

**Comment by luciusmagn** [comment]
I will tell you more once I get home, but as far as I am concerned, we aren't even sure if we are going to be statically-typed or dynamically typed.

**Comment by rustysec** [comment]
I have thought about something like a value type as well. Especially when considering how to handle empty types (something like () or null). I brought this up (in a way) when discussing #45. I have a working implementation, but things come off the rails if you don't return a value from a loop. Currently we just throw an assignment error at run time, but it would be nice to more gracefully handle this.

I implemented a Null type on the plane the other day, but I'm not entirely sure I'm happy with it. There's just a design question that needs to be settled on.

For what it's worth, I cast my vote in the statically typed column. I think that integrates well with rust, and will (probably) allow the performance to stay at a high level.

**Comment by luciusmagn** [comment]
I am leaning towards static typing as well. I wouldn't introduce Null, in alignment with Rust. I wonder if using unit/() for both nully things and void would be a bad solution.

**Comment by rustysec** [comment]
The "Null" type i created is just an abstraction over (), but again I still haven't convinced myself it's a good idea.

**Comment by luciusmagn** [comment]
If it maps to () directly, then that sounds great, although I wouldn't call it Null, since in Rust, even a unit is something :D

Do you have these experiments in your fork? I'd love to take a peek

**Comment by rustysec** [comment]
I haven't pushed them up yet since I'm still writing test cases. My original thought was to call the type "Empty" or something along those lines. I can get a branch on github for further discussion in the next couple days.

**Comment by luciusmagn** [comment]
Awesome. I'd probably call it 'Unit' for parity with Rust, but anything goes at the moment. Nothing is set in stone yet, haha

**Comment by stevedonovan** [comment]
`Box<Any>` is just so damn convenient, there are only a few restrictions. One being the ```'static``` lifetime requirement (no borrows) but generally one has to write structs carefully to use in Rhai anyway.  As for static typing, I'd say that the space of statically-typed scripting languages is an exciting place to be (e.g. Lily). Type inference could get tricky though.

**Comment by stevedonovan** [comment]
I've been having (useful) fun working with the `JsonValue` type (from json crate) within Rhai scripts.

+1 for static typing, but don't underestimate the work involved. The techniques for inference etc are standard but designing a type system that doesn't get in the way is non-trivial. For instance, consider auto-conversion of numbers, strings etc to the underlying `Value` enum. Then can still say `[42,"answer"]` etc

**Comment by schungx** [comment]
> `Box<Any>` is just so damn convenient

It certainly is damn convenient!  Not sure if it helps on execution speed (probably does), but somebody probably needs to benchmark it to know...
