### ISSUE TITLE
variable not found in scope

### ISSUE THREAD

**Issue by jice-nospam** [jonathandturner/rhai#66]
I evaluate this script :
```
let angle=0.0;
fn update() {
    angle += 0.1;
}
```

Then when I try to evaluate `"update()"` using the same scope, I've got a `ErrorVariableNotFound("angle")` even though I see the variable in my scope :
```
[("angle", Any)]
```

Is it not supposed to work this way ?

**Comment by torkleyy** [comment]
You would have to pass `angle` to the `update` function for this to work. Functions don't capture their environment in Rhai.

**Comment by jice-nospam** [comment]
In my case, the caller doesn't even know the variable exist because it's created by the script part. I'm working on a fantasy console with scripted cartridges written in rhai. This is only possible if the script is able to create and use global variables.

I've submitted a pull request that make functions aware of the scope but if it's not what you want for rhai, I'll use my forked version.

**Comment by torkleyy** [comment]
Maybe you just want globals instead of capturing the environment?

**Comment by torkleyy** [comment]
cc @jonathandturner @luciusmagn

**Comment by jice-nospam** [comment]
Indeed, I only need global variables

**Comment by luciusmagn** [comment]
I'll look into it ASAP

2018-03-26 14:17 GMT+02:00 jice-nospam <notifications@github.com>:
