### ISSUE TITLE
Boolean short-circuiting with && and ||

### ISSUE THREAD

**Issue by stevedonovan** [jonathandturner/rhai#68]
This bit me yesterday where I had this kind of situation:

```
cheap_condition() && expensive_condition()
```
Of course, I unconsciously assumed that `expensive_condition` would not be called if `cheap_condition()` was true, but that's not how Rhai works: everything is a function call requiring arguments to be evaluated.

It would be useful to special-case `&&` and `||` since most of us probably expect the standard behaviour.

**Comment by luciusmagn** [comment]
Ah yes, shortcircuiting should be the correct behavior. I will look into it

2018-04-04 9:53 GMT+02:00 Steve J Donovan <notifications@github.com>:

**Comment by schungx** [comment]
PR https://github.com/jonathandturner/rhai/pull/98 implements short-circuiting for `&&` and `||`.  `&` and `|` continues to evaluate all operands.
