### ISSUE TITLE
Better Error Messages

### ISSUE THREAD

**Issue by stevedonovan** [jonathandturner/rhai#75]
I've been playing with generating better error messages:

```
examples$ cargo run --example repl
> f([1,2])
error: Function not found: f (array)
> x + 1
error: Variable not found: x
> 1 + 2.0
error: Function not found: + (i64,f64)
```
Fairly minimal changes (mostly to how errors are displayed).

Any interest in a PR?

(in the _first_ case, could indicate that there is no such function `f`. We can dump all the overloaded functions matching a name, but that might be too noisy)

**Comment by timfish** [comment]
This sounds great. 

It would also be awesome to get character ranges for errors so that the can be squiggly underlined in any under interface!

**Comment by schungx** [comment]
> It would also be awesome to get character ranges for errors so that they can be squiggly underlined in a under interface!

Line number and character position added to error messages in https://github.com/jonathandturner/rhai/pull/97
