### ISSUE TITLE
Runtime Error Handling: A Minimal Proposal

### ISSUE THREAD

**Issue by stevedonovan** [jonathandturner/rhai#78]
Not having error handling (other than panicking) is a problem when integrating non-trivial Rust code with Rhai.  This proposal basically adds unchecked exceptions so that functions can terminate script execution with a clean error.

First, `EvalAltResult` gets a new variant, `ErrorRuntime(String)`. A user-defined function may 'throw' a Rhai exception by returning a `Result<T,EvalAltResult>`; a Rhai function may call a predefined `throw` function.

Implementation is fairly straightforward. We keep a map of type ids for all `Result<T,EvalAltResult>` of interest, providing a closure that can match this for each specific `T` and return a `Result<Box<Any>,EvalAltResult>` which Rhai passes on. These closures are created in `register_type` (finally, no longer a no-op!)

There will be some overhead with doing a hash lookup on all returned values, and with re-boxing 'exception' values.

This is implementable now, as an incremental step towards either Rust-style explicit result handling or catchable exceptions.

**Comment by stevedonovan** [comment]
There's an experimental implementation at https://github.com/stevedonovan/rhai, runtime-errors branch. Seems to work fine, although I wonder if `raise` is not a better word than `throw` :)

But I won't immediately submit a PR since this is something that needs to be discussed first.

**Comment by schungx** [comment]
I can take a whack at it.  Probably simple to extend the `return` functionality.

**Comment by schungx** [comment]
Turns out it is quite easy to add.  Already did.

**Comment by schungx** [comment]
Closed by https://github.com/jonathandturner/rhai/pull/104
