### ISSUE TITLE
Equality Operator Too Strict?

### ISSUE THREAD

**Issue by stevedonovan** [jonathandturner/rhai#79]
I hit this one while experimenting with for-loops https://github.com/stevedonovan/rhai/tree/for-stmt:
```rust
for a in [1,"hello","dolly"] {
  if a == "hello" { //
      break
  }
}
```
Which one would expect to work from exposure to other dynamic languages. However, `==` is not defined for (integer,string) so we get a complaint!

I feel that `==` needs special treatment; if the types are different, then it will always return false, otherwise match the desired type exactly.  Not a difficult thing to do, and faster than checking the whole overloaded set of `==` functions, but deserving of discussion.

The other option is to move towards strict, static typing but that would take a good deal of work!

**Comment by schungx** [comment]
Having this will require providing each operator with a range of possible type combinations...  and it will be impossible to add custom types to the mix.

What about something like a built in `is_string()`, `is_number()` etc. functions?

~~~rust
for a in [1,"hello","dolly"] {
  if is_string(a) {
    if a == "hello" { //
      break
    }
  }
}
~~~

**Comment by schungx** [comment]
PR https://github.com/jonathandturner/rhai/pull/98 implements this feature.

When the `Engine` doesn't find a useable comparison function, it returns `false`.
