### ISSUE TITLE
related scripting language: ketos

### ISSUE THREAD

**Issue by vks** [jonathandturner/rhai#8]
[Ketos](https://github.com/murarth/ketos) is a related embedded Lisp dialect for Rust. I thought you might want to include this in your readme.

**Comment by jonathandturner** [comment]
Cool, will have to check it out.  For this related, I meant more like "languages that are similar or ones that I looked at when I built Rhai".  

Speaking of, though... You inspired me to do a PR for libs.rs so that we can keep the list in one place: https://github.com/nasa42/libs.rs/pull/17

**Comment by jonathandturner** [comment]
(leaving open until I can confirm the PR went in or not)

**Comment by jonathandturner** [comment]
I've updated the readme to point at the new http://libs.rs/scripting/
