### ISSUE TITLE
Use std:any::type_name rather than register_type_name

### ISSUE THREAD

**Issue by timfish** [jonathandturner/rhai#88]
Rust 1.38.0 [now supports](https://doc.rust-lang.org/beta/std/any/fn.type_name.html) `std:any::type_name` which means `engine.register_type_name` could eventually be removed.

**Comment by jonathandturner** [comment]
@timfish - interested in working on a PR for this, by chance?

**Comment by timfish** [comment]
Yes, would like to have a go. 

Is it ok to lose backwards compatibility with anything before 1.38?

**Comment by jonathandturner** [comment]
@timfish - Yes, that's okay
