### ISSUE TITLE
Engine is neither Send nor Sync

### ISSUE THREAD

**Issue by NyxCode** [jonathandturner/rhai#91]
Sadly, `Engine` is neither `Sync` nor `Send`, which makes it difficult to use in things like game engines where there's a lot of concurrency.
I'm not sure if that's easily doable because rhai seems to heavily depend on boxed closures, and just requiring a `F + Sync + Send` would probably break a lot of code..

**Comment by schungx** [comment]
Although `Engine` may not be `Send + Sync`, it is possible to make a `Scope` `Send + Sync`, meaning that you can share variables and values freely across threads.  That means that you'll have a separate `Engine` instance for every thread/task, which might not be that big a deal as `Engine` is pretty light-weight.  You may not want to share an `Engine` across tasks.

**Comment by schungx** [comment]
PR #https://github.com/jonathandturner/rhai/pull/123 has a feature `sync` that makes `Engine`, `Scope` and `AST` `Send + Sync`.
