### ISSUE TITLE
Unable to register_fn

### ISSUE THREAD

**Issue by amithendin** [jonathandturner/rhai#92]
tried to use register_fn. code compiles without errors but when i use the function i registered in code i got an error from the engine saying there is no such a function, same error as when i ran it without the register_fn statement. Tried doing it like this too RegisterFn::register_fn(&mut engine, "name", func);
but still same results. Also could not get the eval to return array from the script something about no clone for [f32] might be a rust problem but work around should be built in the language for returning arrays. The idea of the language and the syntax and the way you use it in code looks super cool and lightwieght and perfect for what I'm trying to do but honestly without a working register_fn or returning arrays there really isn't any way to get useful output from this engine thus rendering it useless. Thanks for making it but just thought id let you know my experience.

**Comment by ndr-brt** [comment]
try import trait RegisterFn:
`use self::rhai::RegisterFn;`
