### ISSUE TITLE
Option to eval without mutating Engine

### ISSUE THREAD

**Issue by Imberflur** [jonathandturner/rhai#99]
In some cases, I don't need the script to define any functions instead I want it to perform some calculations and return a value without modifying the engine. This could be accomplished by having the script define a function and then use `engine.call_fn` but this requires that initial mutation of the engine to define that function.

**Comment by schungx** [comment]
What is wrong with just `eval`?  Pass in your function script and it gets evaluated...

**Comment by schungx** [comment]
https://github.com/jonathandturner/rhai/pull/98

In this PR, `Engine` cleans up after itself.
